#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# Instalar dependencias de Node.js y compilar CSS con Tailwind 4
cd /app
npm install
npm run build

python manage.py migrate
exec python manage.py runserver_plus 0.0.0.0:8000
