# Generated by Django 5.0.11 on 2025-04-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationitem',
            name='term',
            field=models.CharField(blank=True, choices=[('primera', 'Primera evaluación'), ('segunda', 'Segunda evaluación'), ('tercera', 'Tercera evaluación')], null=True),
        ),
    ]
