# Generated by Django 5.0.11 on 2025-04-08 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_evaluationitem_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='RubricCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('max_points', models.PositiveSmallIntegerField(default=2)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('evaluation_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rubric_categories', to='evaluations.evaluationitem')),
            ],
            options={
                'verbose_name': 'Categoría de rúbrica',
                'verbose_name_plural': 'Categorías de rúbrica',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RubricCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='evaluations.rubriccategory')),
            ],
            options={
                'verbose_name': 'Criterio de rúbrica',
                'verbose_name_plural': 'Criterios de rúbrica',
                'ordering': ['-points'],
            },
        ),
        migrations.CreateModel(
            name='RubricScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveSmallIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='evaluations.rubriccategory')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_scores', to='evaluations.evaluation')),
            ],
            options={
                'unique_together': {('evaluation', 'category')},
            },
        ),
    ]
