# Generated by Django 5.0.11 on 2025-04-14 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0006_evaluation_classroom_submission_evaluation_max_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['user__name']},
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PendingEvaluationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_submission', models.BooleanField(default=False, verbose_name='Entrega por classroom')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluation_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_statuses', to='evaluations.evaluationitem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_statuses', to='evaluations.student')),
            ],
            options={
                'verbose_name': 'Estado de evaluación pendiente',
                'verbose_name_plural': 'Estados de evaluaciones pendientes',
                'unique_together': {('student', 'evaluation_item')},
            },
        ),
    ]
