# Generated by Django 5.0.11 on 2025-04-14 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0007_alter_student_options_student_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
    ]
