# Generated by Django 5.0.11 on 2025-05-22 08:12

import django.db.models.deletion
import evaluations.submission_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0010_evaluation_feedback_evaluation_sent_by_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pending_status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='evaluations.pendingevaluationstatus')),
            ],
            options={
                'verbose_name': 'Entrega de Classroom',
                'verbose_name_plural': 'Entregas de Classroom',
            },
        ),
        migrations.CreateModel(
            name='SubmissionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=evaluations.submission_models.submission_image_path, verbose_name='Imagen')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='evaluations.classroomsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=evaluations.submission_models.submission_video_path, verbose_name='Vídeo')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='evaluations.classroomsubmission')),
            ],
        ),
    ]
