# Generated by Django 5.0.11 on 2025-05-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0011_classroomsubmission_submissionimage_submissionvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationitem',
            name='ai_prompt',
            field=models.TextField(blank=True, help_text='Prompt para Gemini que reescribirá la retroalimentación'),
        ),
    ]
