# Generated by Django 5.0.11 on 2025-05-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0012_evaluationitem_ai_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingevaluationstatus',
            name='feedback',
            field=models.TextField(blank=True, verbose_name='Retroalimentación'),
        ),
    ]
