# Generated by Django 5.0.11 on 2025-05-24 17:37

import evaluations.submission_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0013_pendingevaluationstatus_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionvideo',
            name='compressed_video',
            field=models.FileField(blank=True, null=True, upload_to=evaluations.submission_models.submission_compressed_video_path, verbose_name='Vídeo Comprimido'),
        ),
        migrations.AddField(
            model_name='submissionvideo',
            name='processing_error',
            field=models.TextField(blank=True, null=True, verbose_name='Error de Procesamiento'),
        ),
        migrations.AddField(
            model_name='submissionvideo',
            name='processing_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], default='PENDING', max_length=20, verbose_name='Estado de Procesamiento'),
        ),
        migrations.AlterField(
            model_name='submissionvideo',
            name='video',
            field=models.FileField(upload_to=evaluations.submission_models.submission_video_path, verbose_name='Vídeo Original'),
        ),
    ]
