# Generated by Django 5.0.11 on 2025-06-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0014_submissionvideo_compressed_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationitem',
            name='allow_classroom_submission',
            field=models.BooleanField(default=False, verbose_name='Permitir entrega por classroom'),
        ),
        migrations.AddField(
            model_name='evaluationitem',
            name='classroom_reduces_points',
            field=models.BooleanField(default=False, verbose_name='Entrega por classroom resta puntos'),
        ),
    ]
