# Generated by Django 5.0.11 on 2025-06-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0015_evaluationitem_allow_classroom_submission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationitem',
            name='allow_classroom_submission',
        ),
        migrations.AddField(
            model_name='evaluationitem',
            name='force_web_submission',
            field=models.BooleanField(default=False, help_text='Si está activado, todos los alumnos deberán entregar por la web y no por Classroom', verbose_name='Forzar entrega por web'),
        ),
    ]
