# Generated by Django 5.0.11 on 2025-06-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0016_remove_evaluationitem_allow_classroom_submission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationitem',
            name='info_url',
            field=models.URLField(blank=True, help_text='URL con información adicional sobre esta evaluación para los estudiantes', verbose_name='URL de información'),
        ),
        migrations.AlterField(
            model_name='evaluationitem',
            name='force_web_submission',
            field=models.BooleanField(default=False, help_text='Si está activado, todos los alumnos deberán entregar por la web y no en clase', verbose_name='Forzar entrega por web'),
        ),
    ]
