# Generated by Django 5.0.11 on 2025-11-12 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_group_data(apps, schema_editor):
    """
    Migrar datos de Student.group (CharField) a modelo Group y actualizar FKs.
    """
    Student = apps.get_model('evaluations', 'Student')
    Group = apps.get_model('evaluations', 'Group')
    
    # Obtener nombres únicos de grupos existentes
    group_names = Student.objects.values_list('group_old', flat=True).distinct()
    
    # Crear instancias de Group para cada nombre único
    group_map = {}
    for name in group_names:
        if name:  # Ignorar nombres vacíos
            group, created = Group.objects.get_or_create(name=name)
            group_map[name] = group
    
    # Actualizar Student.group_fk con las instancias de Group
    for student in Student.objects.all():
        if student.group_old and student.group_old in group_map:
            student.group_fk = group_map[student.group_old]
            student.save(update_fields=['group_fk'])


def reverse_migrate_group_data(apps, schema_editor):
    """
    Revertir migración: copiar Group.name de vuelta a Student.group_old.
    """
    Student = apps.get_model('evaluations', 'Student')
    
    for student in Student.objects.all():
        if student.group_fk:
            student.group_old = student.group_fk.name
            student.save(update_fields=['group_old'])


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('evaluations', '0017_evaluationitem_info_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Paso 1: Actualizar opciones del modelo Student
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['user__name'], 'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        
        # Paso 2: Renombrar campo group actual a group_old (temporal)
        migrations.RenameField(
            model_name='student',
            old_name='group',
            new_name='group_old',
        ),
        
        # Paso 3: Crear modelo Group
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre del grupo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teachers', models.ManyToManyField(blank=True, help_text='Profesores que imparten clase a este grupo', related_name='teaching_groups', to=settings.AUTH_USER_MODEL, verbose_name='Profesores')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['name'],
            },
        ),
        
        # Paso 4: Añadir campo group_fk temporal (nullable)
        migrations.AddField(
            model_name='student',
            name='group_fk',
            field=models.ForeignKey(
                null=True,
                blank=True,
                help_text='Grupo al que pertenece el estudiante',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='students',
                to='evaluations.group',
                verbose_name='Grupo'
            ),
        ),
        
        # Paso 5: Migrar datos
        migrations.RunPython(migrate_group_data, reverse_migrate_group_data),
        
        # Paso 6: Hacer group_fk no nullable
        migrations.AlterField(
            model_name='student',
            name='group_fk',
            field=models.ForeignKey(
                help_text='Grupo al que pertenece el estudiante',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='students',
                to='evaluations.group',
                verbose_name='Grupo'
            ),
        ),
        
        # Paso 7: Eliminar campo group_old
        migrations.RemoveField(
            model_name='student',
            name='group_old',
        ),
        
        # Paso 8: Renombrar group_fk a group
        migrations.RenameField(
            model_name='student',
            old_name='group_fk',
            new_name='group',
        ),
        
        # Paso 9: Crear modelo GroupLibraryItem
        migrations.CreateModel(
            name='GroupLibraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Notas del profesor sobre este elemento para el grupo', verbose_name='Notas')),
                ('added_by', models.ForeignKey(blank=True, help_text='Profesor que añadió este elemento', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Añadido por')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_items', to='evaluations.group', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Item de Biblioteca de Grupo',
                'verbose_name_plural': 'Items de Biblioteca de Grupo',
                'ordering': ['-added_at'],
                'indexes': [models.Index(fields=['group', '-added_at'], name='evaluations_group_i_d546e2_idx'), models.Index(fields=['content_type', 'object_id'], name='evaluations_content_ed348d_idx')],
                'unique_together': {('group', 'content_type', 'object_id')},
            },
        ),
    ]
