# Generated by Django 5.0.11 on 2025-11-12 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('evaluations', '0018_add_group_model_and_library'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha de la sesión')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('notes', models.TextField(blank=True, help_text='Notas generales sobre la sesión', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_sessions', to='evaluations.group', verbose_name='Grupo')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Profesor')),
            ],
            options={
                'verbose_name': 'Sesión de Clase',
                'verbose_name_plural': 'Sesiones de Clase',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassSessionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('notes', models.TextField(blank=True, help_text='Notas específicas para este elemento en la sesión', verbose_name='Notas')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='evaluations.classsession', verbose_name='Sesión')),
            ],
            options={
                'verbose_name': 'Item de Sesión',
                'verbose_name_plural': 'Items de Sesión',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['teacher', '-date'], name='evaluations_teacher_250224_idx'),
        ),
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['group', '-date'], name='evaluations_group_i_24c479_idx'),
        ),
        migrations.AddIndex(
            model_name='classsessionitem',
            index=models.Index(fields=['session', 'order'], name='evaluations_session_3e7baf_idx'),
        ),
    ]
