# Generated by Django 5.0.11 on 2025-11-13 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0003_rename_evaluations_class_s_teacher_5d3e0a_idx_evaluations_teacher_250224_idx_and_more'),
        ('evaluations', '0019_add_class_sessions'),
    ]

    state_operations = [
        migrations.RemoveField(
            model_name='classsessionitem',
            name='session',
        ),
        migrations.RemoveField(
            model_name='classsessionitem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='group',
            name='teachers',
        ),
        migrations.RemoveField(
            model_name='grouplibraryitem',
            name='group',
        ),
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.AlterUniqueTogether(
            name='grouplibraryitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='grouplibraryitem',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='grouplibraryitem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AlterField(
            model_name='pendingevaluationstatus',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_statuses', to='clases.student'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='clases.student'),
        ),
        migrations.DeleteModel(
            name='ClassSession',
        ),
        migrations.DeleteModel(
            name='ClassSessionItem',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='GroupLibraryItem',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations,
            database_operations=[]
        )
    ]
