# Generated by Django 5.0.11 on 2026-09-19 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=220, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=220, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=220, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('jamzone', 'JamZone'), ('propio', 'Propia')], db_index=True, default='jamzone', max_length=10)),
                ('fuente_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('slug_externo', models.CharField(blank=True, max_length=220)),
                ('titulo', models.CharField(max_length=300)),
                ('anio', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('decada', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('num_acordes', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('tempo', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('progresion_romana', models.CharField(blank=True, max_length=120)),
                ('g_rated', models.BooleanField(default=False)),
                ('spotify_id', models.CharField(blank=True, max_length=64)),
                ('youtube_id', models.CharField(blank=True, max_length=32)),
                ('lyrics_url', models.URLField(blank=True, max_length=500)),
                ('forma', models.JSONField(blank=True, default=list)),
                ('dato', models.TextField(blank=True)),
                ('notas', models.TextField(blank=True, help_text='Tus notas: cómo fue, con qué grupo, qué cambiarías.')),
                ('cursos', models.JSONField(blank=True, default=list, help_text='Cursos donde la has usado o la quieres usar.')),
                ('favorito', models.BooleanField(default=False)),
                ('importado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('artistas', models.ManyToManyField(blank=True, related_name='canciones', to='repertorio.artista')),
                ('generos', models.ManyToManyField(blank=True, related_name='canciones', to='repertorio.genero')),
                ('idiomas', models.ManyToManyField(blank=True, related_name='canciones', to='repertorio.idioma')),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(choices=[('original', 'Tonalidad original'), ('transposed', 'Tonalidad fácil')], max_length=20)),
                ('nivel', models.CharField(blank=True, choices=[('Beginner', 'Principiante'), ('Intermediate', 'Intermedio'), ('Advanced', 'Avanzado')], db_index=True, max_length=20)),
                ('tonalidad', models.CharField(blank=True, max_length=20)),
                ('acordes', models.JSONField(blank=True, default=list)),
                ('instrumentos', models.JSONField(blank=True, default=list)),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='repertorio.cancion')),
            ],
            options={
                'ordering': ['version'],
            },
        ),
        migrations.AddIndex(
            model_name='cancion',
            index=models.Index(fields=['decada', 'num_acordes'], name='repertorio__decada_bde2fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='version',
            unique_together={('cancion', 'version')},
        ),
    ]
