# Generated by Django 5.0.11 on 2026-09-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repertorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sincronizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momento', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('automatica', models.BooleanField(default=False)),
                ('recibidas', models.PositiveIntegerField(default=0)),
                ('creadas', models.PositiveIntegerField(default=0)),
                ('actualizadas', models.PositiveIntegerField(default=0)),
                ('sin_cambios', models.PositiveIntegerField(default=0)),
                ('campos_respetados', models.PositiveIntegerField(default=0)),
                ('huerfanos_borrados', models.PositiveIntegerField(default=0)),
                ('fallos', models.PositiveIntegerField(default=0)),
                ('detalle', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Sincronizaciones',
                'ordering': ['-momento'],
            },
        ),
        migrations.AddField(
            model_name='cancion',
            name='bloqueados',
            field=models.JSONField(blank=True, default=list, help_text='Campos corregidos a mano que la importación no debe tocar.'),
        ),
    ]
