# Generated by Django 5.0.11 on 2026-09-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repertorio', '0002_sincronizacion_cancion_bloqueados'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='progresion_familia',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
    ]
