# Generated by Django 5.0.11 on 2026-09-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repertorio', '0004_calcular_familias_de_progresion'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='es_menor',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='version',
            name='tonalidad',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
