# Generated by Django 5.0.11 on 2026-09-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='acceso_con_contrasena',
            field=models.BooleanField(default=False, help_text='Para las cuentas de fuera del centro, que da de alta el administrador a mano. Quien tiene correo del centro entra con Google y no necesita esto.', verbose_name='Puede entrar con contraseña'),
        ),
    ]
