volumes:
  stage_postgres_data: {}
  stage_postgres_data_backups: {}
  stage_django_media: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: martina_bescos_app_stage_django
    volumes:
      - stage_django_media:/app/martina_bescos_app/media
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    networks:
      - app-martina-stage-network

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: martina_bescos_app_stage_postgres
    volumes:
      - stage_postgres_data:/var/lib/postgresql/data
      - stage_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres
    networks:
      - app-martina-stage-network

  redis:
    image: docker.io/redis:6
    networks:
      - app-martina-stage-network

  nginx_stage:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: martina_bescos_app_stage_nginx
    depends_on:
      - django
    volumes:
      - stage_django_media:/usr/share/nginx/media:ro
    networks:
      - app-martina-stage-network
      - nginx-proxy-manager-net

networks:
  app-martina-stage-network:
    driver: bridge
  nginx-proxy-manager-net:
    external: true
    name: nginx-proxy-manager_default
