volumes:
  martina_bescos_app_local_postgres_data: {}
  martina_bescos_app_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: martina_bescos_app_local_django
    container_name: martina_bescos_app_local_django
    depends_on:
      - postgres
      - mailpit
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

    networks:
      - app-martina-network
      - nginx-proxy-manager-net

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: martina_bescos_app_production_postgres
    container_name: martina_bescos_app_local_postgres
    volumes:
      - ./martina_bescos_app_local_postgres_data:/var/lib/postgresql/data
      - ./martina_bescos_app_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

    networks:
      - app-martina-network

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: martina_bescos_app_local_mailpit
    ports:
      - "8025:8025"

    networks:
      - app-martina-network

networks:
  app-martina-network:
    driver: bridge
  nginx-proxy-manager-net:
    external: true
    name: nginx-proxy-manager_default
