volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_django_media: {}

services:
  django: &django-base
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: martina_bescos_app_production_django
    container_name: martina_bescos_app_production_django
    volumes:
      - production_django_media:/app/martina_bescos_app/media
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    networks:
      - app-martina-production-network

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: martina_bescos_app_production_postgres
    container_name: martina_bescos_app_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres
    networks:
      - app-martina-production-network

  redis:
    image: docker.io/redis:6
    container_name: martina_bescos_app_production_redis
    networks:
      - app-martina-production-network

  huey_consumer:
    <<: *django-base
    image: martina_bescos_app_production_django
    container_name: martina_bescos_app_production_huey_consumer
    depends_on:
      - postgres
      - redis
    ports: []
    command: /start-huey

  nginx_production:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: martina_bescos_app_production_nginx
    container_name: martina_bescos_app_production_nginx
    depends_on:
      - django
    volumes:
      - production_django_media:/usr/share/nginx/media:ro
    networks:
      - app-martina-production-network
      - nginx-proxy-manager-net

networks:
  app-martina-production-network:
    driver: bridge
  nginx-proxy-manager-net:
    external: true
    name: nginx-proxy-manager_default
