# Generated by Django 5.0.11 on 2026-09-06 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoWifi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(db_index=True, help_text='Forma canónica AA:BB:CC:DD:EE:FF, en mayúsculas.', max_length=17, verbose_name='Dirección MAC')),
                ('descripcion', models.CharField(blank=True, default='', help_text='Para reconocerlo después: «móvil personal», «portátil del aula 12»…', max_length=120, verbose_name='Dispositivo')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de dar de alta'), ('anadida', 'Dada de alta'), ('baja_pendiente', 'Pendiente de dar de baja'), ('dada_de_baja', 'Dada de baja')], db_index=True, default='pendiente', max_length=16, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Solicitado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('anadida_at', models.DateTimeField(blank=True, null=True, verbose_name='Dado de alta')),
                ('baja_at', models.DateTimeField(blank=True, null=True, verbose_name='Dado de baja')),
                ('notificado_at', models.DateTimeField(blank=True, help_text='Sello del correo con la clave. Impide enviarlo dos veces.', null=True, verbose_name='Aviso enviado')),
                ('anadida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='altas_wifi_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Dado de alta por')),
                ('baja_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bajas_wifi_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Dado de baja por')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos_wifi', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Dispositivo WiFi',
                'verbose_name_plural': 'Dispositivos WiFi',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='dispositivowifi',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'dada_de_baja'), _negated=True), fields=('mac',), name='wifi_mac_unica_mientras_activa'),
        ),
    ]
