# Generated by Django 5.0.11 on 2026-09-24 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivowifi',
            name='solicitado_por',
            field=models.ForeignKey(blank=True, help_text='Quien lo dio de alta desde administración en nombre del solicitante, sin que este entrara con Google. Vacío si lo pidió él mismo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='altas_wifi_en_nombre_de_otros', to=settings.AUTH_USER_MODEL, verbose_name='Registrado a mano por'),
        ),
    ]
