# Generated by Django 5.0.11 on 2025-11-13 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0002_add_default_subject'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='classsession',
            new_name='evaluations_teacher_250224_idx',
            old_name='evaluations_class_s_teacher_5d3e0a_idx',
        ),
        migrations.RenameIndex(
            model_name='classsession',
            new_name='evaluations_group_i_24c479_idx',
            old_name='evaluations_class_s_group_i_7f42c1_idx',
        ),
        migrations.RenameIndex(
            model_name='classsessionitem',
            new_name='evaluations_session_3e7baf_idx',
            old_name='evaluations_class_s_session_892a3c_idx',
        ),
        migrations.RenameIndex(
            model_name='grouplibraryitem',
            new_name='evaluations_group_i_d546e2_idx',
            old_name='evaluations_group_i_group_id_64e65f_idx',
        ),
        migrations.RenameIndex(
            model_name='grouplibraryitem',
            new_name='evaluations_content_ed348d_idx',
            old_name='evaluations_group_i_content_6a12b6_idx',
        ),
    ]
