# Generated by Django 5.0.11 on 2025-11-19 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0003_rename_evaluations_class_s_teacher_5d3e0a_idx_evaluations_teacher_250224_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouplibraryitem',
            name='group_proficiency_level',
            field=models.PositiveSmallIntegerField(choices=[(1, '⭐ El grupo apenas lo conoce'), (2, '⭐⭐ Lo está aprendiendo'), (3, '⭐⭐⭐ Lo trabaja con soltura'), (4, '⭐⭐⭐⭐ Lo domina muy bien')], default=1, help_text='Nivel de dominio de este contenido por el grupo (1-4)', verbose_name='Nivel del grupo'),
        ),
    ]
