# Generated by Django 5.0.11 on 2025-12-11 22:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0004_grouplibraryitem_group_proficiency_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único del enlace de invitación', unique=True, verbose_name='Token de invitación')),
                ('is_active', models.BooleanField(default=True, help_text='Si está desactivada, el enlace deja de funcionar', verbose_name='Activa')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Déjalo vacío para usos ilimitados', null=True, verbose_name='Número máximo de usos')),
                ('uses', models.PositiveIntegerField(default=0, verbose_name='Usos realizados')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira el')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Último uso')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_group_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='clases.group', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Invitación a grupo',
                'verbose_name_plural': 'Invitaciones a grupos',
                'ordering': ['-created_at'],
            },
        ),
    ]
