# Generated by Django 5.0.11 on 2025-12-11 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0005_groupinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['user__name'], 'verbose_name': 'Estudiante (Legacy)', 'verbose_name_plural': 'Estudiantes (Legacy)'},
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(help_text='Grupo al que pertenece el estudiante (DEPRECADO: usar Enrollment)', on_delete=django.db.models.deletion.PROTECT, related_name='students', to='clases.group', verbose_name='Grupo'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de matrícula')),
                ('is_active', models.BooleanField(default=True, help_text='Si está desactivado, el usuario no verá este grupo', verbose_name='Activo')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='clases.group', verbose_name='Grupo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'ordering': ['-enrolled_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='clases_enro_user_id_d53b8e_idx'), models.Index(fields=['group', 'is_active'], name='clases_enro_group_i_711b3e_idx')],
                'unique_together': {('user', 'group')},
            },
        ),
    ]
