# Generated by Django 5.0.11 on 2026-03-23 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0007_migrate_students_to_enrollments'),
        ('cms', '0019_blog_featured_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsessionitem',
            name='source_scorepage',
            field=models.ForeignKey(blank=True, help_text='ScorePage desde la que se añadió este elemento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_items_from', to='cms.scorepage', verbose_name='ScorePage de origen'),
        ),
    ]
