# Generated by Django 5.0.11 on 2026-03-23 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0008_add_source_scorepage_to_classsessionitem'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        # Step 1: Rename the field (preserves data)
        migrations.RenameField(
            model_name='classsessionitem',
            old_name='source_scorepage',
            new_name='source_page',
        ),
        # Step 2: Alter the field to point to wagtailcore.Page instead of cms.ScorePage
        migrations.AlterField(
            model_name='classsessionitem',
            name='source_page',
            field=models.ForeignKey(
                blank=True,
                help_text='Página desde la que se añadió este elemento',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='session_items_from',
                to='wagtailcore.page',
                verbose_name='Página de origen',
            ),
        ),
    ]
