# Generated by Django 5.0.11 on 2026-04-15 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0009_rename_source_scorepage_to_source_page'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyCardBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='study_cards/batches/', verbose_name='Archivo PDF')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_card_batches', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_card_batches', to='clases.group', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Lote de Tarjetas',
                'verbose_name_plural': 'Lotes de Tarjetas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyCardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, verbose_name='Código')),
                ('position', models.PositiveIntegerField(verbose_name='Posición')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clases.studycardbatch', verbose_name='Lote')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtailimages.image', verbose_name='Imagen')),
                ('source_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.page', verbose_name='Página de origen')),
            ],
            options={
                'verbose_name': 'Tarjeta',
                'verbose_name_plural': 'Tarjetas',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='StudyCardPickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picked_up_at', models.DateField(verbose_name='Fecha de recogida')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('photo_ocr', 'Photo OCR')], default='manual', max_length=20, verbose_name='Origen')),
                ('confidence', models.FloatField(blank=True, help_text='Confianza del reconocimiento OCR (0-1)', null=True, verbose_name='Confianza OCR')),
                ('card_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickups', to='clases.studycarditem', verbose_name='Tarjeta')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_card_pickups', to=settings.AUTH_USER_MODEL, verbose_name='Alumno')),
            ],
            options={
                'verbose_name': 'Recogida de Tarjeta',
                'verbose_name_plural': 'Recogidas de Tarjetas',
                'ordering': ['-picked_up_at'],
            },
        ),
        migrations.AddIndex(
            model_name='studycarditem',
            index=models.Index(fields=['code'], name='clases_stud_code_76292a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studycarditem',
            unique_together={('batch', 'code')},
        ),
        migrations.AddIndex(
            model_name='studycardpickup',
            index=models.Index(fields=['student', '-picked_up_at'], name='clases_stud_student_2cf5b6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studycardpickup',
            unique_together={('card_item', 'student')},
        ),
    ]
