# Generated by Django 5.0.11 on 2026-04-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0010_study_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studycarditem',
            name='code',
            field=models.CharField(max_length=20, verbose_name='Código'),
        ),
    ]
