# Generated by Django 5.0.11 on 2026-05-04 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0011_study_cards_v2'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyCardLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text='Texto corto que se imprime junto al código (máx. 60 car.)', max_length=60, verbose_name='Descripción')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtailimages.image', verbose_name='Imagen')),
                ('source_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.page', verbose_name='Página de origen')),
            ],
            options={
                'verbose_name': 'Etiqueta de Tarjeta',
                'verbose_name_plural': 'Etiquetas de Tarjetas',
                'unique_together': {('image', 'source_page')},
            },
        ),
    ]
