# Generated by Django 5.0.11 on 2026-09-09 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0013_classsession_reflection'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classsessionitem',
            name='seccion',
            field=models.CharField(blank=True, choices=[('teoria', 'Teoría'), ('ritmo_melodia', 'Ritmo o melodía'), ('dictado', 'Dictado y reconocimiento'), ('sensorialidad', 'Sensorialidad'), ('instrumento', 'Instrumento'), ('cancion', 'Canciones')], max_length=20, verbose_name='Sección de la clase'),
        ),
        migrations.AddField(
            model_name='classsessionitem',
            name='visto',
            field=models.BooleanField(default=False, verbose_name='Visto en clase'),
        ),
        migrations.CreateModel(
            name='GroupBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(choices=[('teoria', 'Teoría'), ('ritmo_melodia', 'Ritmo o melodía'), ('dictado', 'Dictado y reconocimiento'), ('sensorialidad', 'Sensorialidad'), ('instrumento', 'Instrumento'), ('cancion', 'Canciones')], help_text='En qué momento de la clase entra este libro', max_length=20, verbose_name='Sección de la clase')),
                ('modo', models.CharField(choices=[('secuencial', 'Secuencial — avanza y no vuelve'), ('en_curso', 'En curso — sigue activo hasta que lo cierres')], default='secuencial', max_length=12, verbose_name='Modo de avance')),
                ('activo', models.BooleanField(default=True, help_text='Un libro inactivo deja de proponer elementos, sin perder el avance', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Asignado por')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='clases.group', verbose_name='Grupo')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_books', to='wagtailcore.page', verbose_name='Libro')),
            ],
            options={
                'verbose_name': 'Libro del grupo',
                'verbose_name_plural': 'Libros del grupo',
                'ordering': ['group', 'seccion', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='classsessionitem',
            name='group_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_items', to='clases.groupbook', verbose_name='Libro del grupo'),
        ),
        migrations.CreateModel(
            name='GroupBookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('orden', models.PositiveIntegerField(blank=True, help_text='Vacío = el orden del libro', null=True, verbose_name='Orden en el grupo')),
                ('incluido', models.BooleanField(default=True, help_text='Desmarcado: no se propone nunca a este grupo', verbose_name='Incluido')),
                ('a_casa', models.BooleanField(default=False, verbose_name='Baja a las bibliotecas del alumnado')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('visto', 'Visto — no volver a proponerlo'), ('repetir', 'Visto, pero repetirlo')], default='pendiente', max_length=12, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('group_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clases.groupbook', verbose_name='Libro del grupo')),
                ('source_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_book_items_from', to='wagtailcore.page', verbose_name='Capítulo de origen')),
                ('visto_en', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_marcados', to='clases.classsession', verbose_name='Visto en la sesión')),
            ],
            options={
                'verbose_name': 'Elemento de libro del grupo',
                'verbose_name_plural': 'Elementos de libros del grupo',
                'ordering': ['group_book', 'orden'],
            },
        ),
        migrations.AddIndex(
            model_name='groupbook',
            index=models.Index(fields=['group', 'activo'], name='clases_grou_group_i_a0b1ae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupbook',
            unique_together={('group', 'libro')},
        ),
        migrations.AddIndex(
            model_name='groupbookitem',
            index=models.Index(fields=['group_book', 'estado'], name='clases_grou_group_b_62f6ed_idx'),
        ),
        migrations.AddIndex(
            model_name='groupbookitem',
            index=models.Index(fields=['content_type', 'object_id'], name='clases_grou_content_383b09_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupbookitem',
            unique_together={('group_book', 'content_type', 'object_id')},
        ),
    ]
