# Generated by Django 5.0.11 on 2026-09-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0014_classsessionitem_seccion_classsessionitem_visto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='archivado',
            field=models.BooleanField(default=False, help_text='Fuera de las listas del día a día. No borra nada y se puede deshacer', verbose_name='Archivado'),
        ),
    ]
