# Generated by Django 5.0.11 on 2026-09-11 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0015_group_archivado'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupinvitation',
            name='rol',
            field=models.CharField(choices=[('alumnado', 'Alumnado — se matricula en el grupo'), ('profesorado', 'Profesorado — puede usar la aplicación')], default='alumnado', max_length=12, verbose_name='Para quién'),
        ),
        migrations.AlterField(
            model_name='groupinvitation',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='clases.group', verbose_name='Grupo'),
        ),
    ]
