# Generated by Django 5.0.11 on 2026-09-14 17:26

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0016_groupinvitation_rol_alter_groupinvitation_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'base_manager_name': 'todos', 'ordering': ['name', 'subject'], 'verbose_name': 'Grupo', 'verbose_name_plural': 'Grupos'},
        ),
        migrations.AlterModelManagers(
            name='group',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='es_plantilla',
            field=models.BooleanField(default=False, help_text='No tiene alumnado ni sesiones. Se usa para preparar y enviar a los grupos', verbose_name='Plantilla de nivel'),
        ),
    ]
