# Generated by Django 5.0.11 on 2026-09-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0017_alter_group_options_alter_group_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='idioma',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='es', help_text='En la bilingüe, English: sus artículos se abren en inglés', max_length=5, verbose_name='Lengua de la materia'),
        ),
    ]
