# Generated by Django 5.0.11 on 2026-09-24 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0018_group_idioma'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, verbose_name='Texto')),
                ('audio', models.FileField(blank=True, null=True, upload_to='class_reflections/notas/%Y/%m/', verbose_name='Nota de voz')),
                ('item_titulo', models.CharField(blank=True, max_length=255, verbose_name='Título del elemento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas', to='clases.classsessionitem', verbose_name='Elemento en pantalla')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='clases.classsession', verbose_name='Sesión')),
            ],
            options={
                'verbose_name': 'Nota de clase',
                'verbose_name_plural': 'Notas de clase',
                'ordering': ['created_at'],
            },
        ),
    ]
