# Generated by Django 5.0.11 on 2026-09-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0019_sessionnote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionnote',
            name='texto',
        ),
        migrations.AddField(
            model_name='sessionnote',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Transcribiendo'), ('transcrita', 'Transcrita'), ('error', 'No se pudo transcribir')], default='pendiente', max_length=12),
        ),
        migrations.AddField(
            model_name='sessionnote',
            name='transcripcion',
            field=models.TextField(blank=True, verbose_name='Transcripción'),
        ),
    ]
