# Generated by Django 5.0.11 on 2026-10-04 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0020_notas_de_voz_transcritas'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LibroOcultoEnLectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros_ocultos_en_lectura', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Libro oculto en la lista de lectura',
                'verbose_name_plural': 'Libros ocultos en la lista de lectura',
                'unique_together': {('user', 'libro')},
            },
        ),
    ]
