# Generated by Django 5.0.11 on 2026-10-04 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0004_rubrica'),
        ('clases', '0021_libro_oculto_en_lectura'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsessionitem',
            name='instrumento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elementos_de_clase', to='calificaciones.instrumento', verbose_name='Evaluable con'),
        ),
    ]
