# Generated by Django 5.0.11 on 2026-10-04 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0022_evaluable_con_instrumento'),
        ('musica', '0010_etiquetas_de_libro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TonoDeGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semitonos', models.SmallIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tonos', to='clases.group')),
                ('letra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tonos_de_grupo', to='musica.letraconacordes')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tono de una canción para un grupo',
                'verbose_name_plural': 'Tonos de canciones por grupo',
                'unique_together': {('group', 'letra')},
            },
        ),
    ]
