# Generated by Django 5.0.11 on 2026-10-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0023_tono_de_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsessionitem',
            name='tratado',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Tratado en clase'),
        ),
    ]
