# Generated by Django 5.0.11 on 2026-10-07 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0024_tratado_en_clase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaseDeLista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aula', models.CharField(choices=[('referencia', 'Su aula'), ('musica', 'Aula de música')], default='referencia', max_length=12)),
                ('pasada_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pase_de_lista', to='clases.classsession')),
            ],
            options={
                'verbose_name': 'Pase de lista',
                'verbose_name_plural': 'Pases de lista',
            },
        ),
        migrations.CreateModel(
            name='PlanoDeClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aula', models.CharField(choices=[('referencia', 'Su aula'), ('musica', 'Aula de música')], max_length=12, verbose_name='Aula')),
                ('disposicion', models.JSONField(blank=True, default=dict, verbose_name='Disposición')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='clases.group', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Plano de clase',
                'verbose_name_plural': 'Planos de clase',
                'unique_together': {('group', 'aula')},
            },
        ),
        migrations.CreateModel(
            name='PlanoVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposicion', models.JSONField(default=dict)),
                ('origen', models.CharField(choices=[('pantalla', 'Pantalla'), ('api', 'API'), ('restaurar', 'Restaurada')], default='pantalla', max_length=12)),
                ('motivo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='clases.planodeclase')),
            ],
            options={
                'verbose_name': 'Versión de plano',
                'verbose_name_plural': 'Versiones de plano',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('presente', 'Presente'), ('falta', 'Falta'), ('retraso', 'Retraso')], default='presente', max_length=10)),
                ('hora_llegada', models.TimeField(blank=True, null=True)),
                ('sin_material', models.JSONField(blank=True, default=list)),
                ('nota', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='clases.classsession')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'unique_together': {('session', 'alumno')},
            },
        ),
    ]
