# Generated by Django 5.0.11 on 2025-09-24 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('source_object_id', models.PositiveIntegerField()),
                ('custom_settings', models.JSONField(blank=True, default=dict, help_text='Configuraciones específicas en formato JSON')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('generating', 'Generando'), ('ready', 'Lista'), ('error', 'Error')], default='draft', max_length=20)),
                ('html_file', models.FileField(blank=True, null=True, upload_to='presentations/html/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='presentations/pdf/')),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to=settings.AUTH_USER_MODEL)),
                ('source_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PresentationExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(choices=[('html', 'HTML'), ('pdf', 'PDF'), ('pptx', 'PowerPoint')], max_length=10)),
                ('export_settings', models.JSONField(blank=True, default=dict)),
                ('file', models.FileField(upload_to='presentations/exports/')),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completada'), ('failed', 'Fallida')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='presentations.presentation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PresentationSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('slide_type', models.CharField(choices=[('title', 'Título'), ('content', 'Contenido'), ('music_item', 'Elemento Musical'), ('exercise', 'Ejercicio'), ('image', 'Imagen'), ('text', 'Texto'), ('break', 'Descanso')], max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('text_content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='presentations/slides/')),
                ('duration', models.DurationField(blank=True, help_text='Duración estimada de esta diapositiva', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notas del presentador')),
                ('custom_css_class', models.CharField(blank=True, max_length=100)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='presentations.presentation')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PresentationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('template_type', models.CharField(choices=[('class_session', 'Sesión de Clase'), ('music_collection', 'Colección Musical'), ('student_portfolio', 'Portfolio de Estudiante'), ('custom', 'Personalizada')], max_length=20)),
                ('theme', models.CharField(default='default', help_text='Tema visual de la presentación', max_length=50)),
                ('page_format', models.CharField(choices=[('A4', 'A4'), ('A3', 'A3'), ('Letter', 'Letter')], default='A4', max_length=10)),
                ('orientation', models.CharField(choices=[('portrait', 'Vertical'), ('landscape', 'Horizontal')], default='portrait', max_length=10)),
                ('custom_css', models.TextField(blank=True, help_text='CSS adicional para personalizar la presentación')),
                ('is_public', models.BooleanField(default=False, help_text='Disponible para otros usuarios')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentation_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='presentation',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='presentations.presentationtemplate'),
        ),
        migrations.CreateModel(
            name='PresentationShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_level', models.CharField(choices=[('view', 'Solo visualización'), ('edit', 'Puede editar'), ('duplicate', 'Puede duplicar')], default='view', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Fecha de expiración del acceso', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('message', models.TextField(blank=True, help_text='Mensaje para el usuario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='presentations.presentation')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentation_shares_given', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_presentations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('presentation', 'shared_with')},
            },
        ),
    ]
