# Generated by Django 5.0.11 on 2026-02-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevisit',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
