# Generated by Django 5.0.11 on 2026-10-03 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copiar_usuario_de_la_sesion(apps, schema_editor):
    """Atribuye las visitas antiguas al usuario que tenía su sesión.

    Es lo mejor que hay para el histórico: las sesiones que nacieron anónimas
    nunca guardaron usuario, así que esas visitas se quedan sin atribuir.
    """
    PageVisit = apps.get_model('analytics', 'PageVisit')
    UserSession = apps.get_model('analytics', 'UserSession')
    for session_id, user_id in UserSession.objects.filter(
        user__isnull=False
    ).values_list('id', 'user_id'):
        PageVisit.objects.filter(session_id=session_id).update(user_id=user_id)


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_usersession_visitor_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevisit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(copiar_usuario_de_la_sesion, migrations.RunPython.noop),
    ]
