# Generated by Django 5.0.11 on 2025-08-26 09:28

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Índice del Blog',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='StandardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, help_text='Introducción de la página')),
                ('body', wagtail.fields.RichTextField(blank=True, help_text='Contenido principal de la página')),
            ],
            options={
                'verbose_name': 'Página Estándar',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(verbose_name='Fecha de publicación')),
                ('intro', models.CharField(help_text='Resumen del artículo', max_length=250)),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('featured_image', models.ForeignKey(blank=True, help_text='Imagen destacada del artículo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Artículo de Blog',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(blank=True, help_text='Título principal de la página de inicio', max_length=255)),
                ('hero_subtitle', models.CharField(blank=True, help_text='Subtítulo de la página de inicio', max_length=255)),
                ('body', wagtail.fields.RichTextField(blank=True, help_text='Contenido principal de la página')),
                ('hero_image', models.ForeignKey(blank=True, help_text='Imagen principal de la página de inicio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Página de Inicio',
            },
            bases=('wagtailcore.page',),
        ),
    ]
