# Generated by Django 5.0.11 on 2025-09-24 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
        ('cms', '0002_classsessionpage_musicexercisepage_sessionmusicitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsessionpage',
            name='course',
            field=models.ForeignKey(help_text='Curso al que pertenece esta sesión', on_delete=django.db.models.deletion.PROTECT, related_name='wagtail_sessions', to='classroom.course'),
        ),
    ]
