# Generated by Django 5.0.11 on 2025-11-02 08:34

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicComposer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('birth_year', models.PositiveIntegerField(blank=True, null=True)),
                ('death_year', models.PositiveIntegerField(blank=True, null=True)),
                ('bio', wagtail.fields.RichTextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Compositor Musical',
                'verbose_name_plural': 'Compositores Musicales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MusicLibraryIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Texto de introducción para la biblioteca musical')),
            ],
            options={
                'verbose_name': 'Biblioteca Musical',
                'verbose_name_plural': 'Bibliotecas Musicales',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MusicTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#3B82F6', help_text='Código de color hex', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Etiqueta Musical',
                'verbose_name_plural': 'Etiquetas Musicales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SetlistPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.fields.RichTextField(blank=True, help_text='Descripción de este setlist')),
                ('setlist_items', wagtail.fields.StreamField([('score_reference', 0), ('notes', 1), ('separator', 3)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Seleccionar una partitura de tu biblioteca', 'page_type': ['cms.ScorePage']}), 1: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Notas para este elemento del setlist'}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': "Título de sección (ej: 'Intermedio')", 'max_length': 100}), 3: ('wagtail.blocks.StructBlock', [[('title', 2)]], {'icon': 'horizontalrule'})})),
            ],
            options={
                'verbose_name': 'Lista de Reproducción',
                'verbose_name_plural': 'Listas de Reproducción',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MusicCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Clase CSS del icono', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms.musiccategory')),
            ],
            options={
                'verbose_name': 'Categoría Musical',
                'verbose_name_plural': 'Categorías Musicales',
                'ordering': ['name'],
                'unique_together': {('name', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='ScorePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content', wagtail.fields.StreamField([('pdf_score', 4), ('metadata', 12), ('bookmarks', 18), ('notes', 19)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Título del PDF', 'max_length': 200}), 1: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Seleccionar archivo PDF'}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Descripción opcional', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Número de páginas', 'max_length': 10, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('pdf_file', 1), ('description', 2), ('page_count', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'ej: C mayor, F# menor', 'max_length': 20, 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'BPM o indicación de tempo', 'max_length': 20, 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Principiante, Fácil, Intermedio, Avanzado, Experto', 'max_length': 20, 'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 10, 'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': '1-5 estrellas', 'max_length': 5, 'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'Número de catálogo, opus, etc.', 'max_length': 200, 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('composer', 5), ('key_signature', 6), ('tempo', 7), ('difficulty', 8), ('duration_minutes', 9), ('rating', 10), ('reference', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': "Número de página o rango (ej: '5' o '5-8')", 'max_length': 10}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': "Tipo: 'page' para página única, 'item' para rango de páginas", 'max_length': 10}), 16: ('wagtail.blocks.TextBlock', (), {'required': False}), 17: ('wagtail.blocks.StructBlock', [[('title', 13), ('page_number', 14), ('bookmark_type', 15), ('notes', 16)]], {}), 18: ('wagtail.blocks.ListBlock', (17,), {}), 19: ('wagtail.blocks.RichTextBlock', (), {})})),
                ('difficulty_level', models.CharField(blank=True, choices=[('beginner', 'Principiante'), ('easy', 'Fácil'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado'), ('expert', 'Experto')], max_length=20)),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='1-5 estrellas', null=True)),
                ('categories', modelcluster.fields.ParentalManyToManyField(blank=True, to='cms.musiccategory')),
                ('composer', models.ForeignKey(blank=True, help_text='Seleccionar o añadir un compositor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.musiccomposer')),
                ('tags', modelcluster.fields.ParentalManyToManyField(blank=True, to='cms.musictag')),
            ],
            options={
                'verbose_name': 'Partitura',
                'verbose_name_plural': 'Partituras',
            },
            bases=('wagtailcore.page',),
        ),
    ]
