# Generated by Django 5.0.11 on 2025-11-06 07:27

import modelcluster.fields
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_musiccomposer_musiclibraryindexpage_musictag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='cms.musiccategory'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='tags',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='cms.musictag'),
        ),
        migrations.AlterField(
            model_name='scorepage',
            name='content',
            field=wagtail.fields.StreamField([('pdf_score', 4), ('metadata', 12), ('bookmarks', 18), ('notes', 19), ('audio', 22)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Título del PDF', 'max_length': 200}), 1: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Seleccionar archivo PDF'}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Descripción opcional', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Número de páginas', 'max_length': 10, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('pdf_file', 1), ('description', 2), ('page_count', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'ej: C mayor, F# menor', 'max_length': 20, 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'BPM o indicación de tempo', 'max_length': 20, 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Principiante, Fácil, Intermedio, Avanzado, Experto', 'max_length': 20, 'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 10, 'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': '1-5 estrellas', 'max_length': 5, 'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'Número de catálogo, opus, etc.', 'max_length': 200, 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('composer', 5), ('key_signature', 6), ('tempo', 7), ('difficulty', 8), ('duration_minutes', 9), ('rating', 10), ('reference', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': "Número de página o rango (ej: '5' o '5-8')", 'max_length': 10}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': "Tipo: 'page' para página única, 'item' para rango de páginas", 'max_length': 10}), 16: ('wagtail.blocks.TextBlock', (), {'required': False}), 17: ('wagtail.blocks.StructBlock', [[('title', 13), ('page_number', 14), ('bookmark_type', 15), ('notes', 16)]], {}), 18: ('wagtail.blocks.ListBlock', (17,), {}), 19: ('wagtail.blocks.RichTextBlock', (), {}), 20: ('wagtail.blocks.CharBlock', (), {'help_text': 'Título del audio', 'max_length': 200}), 21: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Seleccionar archivo audio'}), 22: ('wagtail.blocks.StructBlock', [[('title', 20), ('audio_file', 21), ('description', 2)]], {})}),
        ),
    ]
