# Generated by Django 5.0.11 on 2025-11-17 12:18

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_make_difficulty_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorepage',
            name='content',
            field=wagtail.fields.StreamField([('pdf_score', 4), ('metadata', 11), ('bookmarks', 17), ('notes', 18), ('audio', 21), ('image', 25), ('embed', 26)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Título del PDF', 'max_length': 200}), 1: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Seleccionar archivo PDF'}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Descripción opcional', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Número de páginas', 'max_length': 10, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('pdf_file', 1), ('description', 2), ('page_count', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'ej: C mayor, F# menor', 'max_length': 20, 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'BPM o indicación de tempo', 'max_length': 20, 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Principiante, Fácil, Intermedio, Avanzado, Experto', 'max_length': 20, 'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 10, 'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Número de catálogo, opus, etc.', 'max_length': 200, 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('composer', 5), ('key_signature', 6), ('tempo', 7), ('difficulty', 8), ('duration_minutes', 9), ('reference', 10)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': "Número de página o rango (ej: '5' o '5-8')", 'max_length': 10}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': "Tipo: 'page' para página única, 'item' para rango de páginas", 'max_length': 10}), 15: ('wagtail.blocks.TextBlock', (), {'required': False}), 16: ('wagtail.blocks.StructBlock', [[('title', 12), ('page_number', 13), ('bookmark_type', 14), ('notes', 15)]], {}), 17: ('wagtail.blocks.ListBlock', (16,), {}), 18: ('wagtail.blocks.RichTextBlock', (), {}), 19: ('wagtail.blocks.CharBlock', (), {'help_text': 'Título del audio', 'max_length': 200}), 20: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Seleccionar archivo audio'}), 21: ('wagtail.blocks.StructBlock', [[('title', 19), ('audio_file', 20), ('description', 2)]], {}), 22: ('wagtail.blocks.CharBlock', (), {'help_text': 'Título de la imagen', 'max_length': 200}), 23: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Seleccionar imagen'}), 24: ('wagtail.blocks.TextBlock', (), {'help_text': 'Texto alternativo para accesibilidad', 'required': False}), 25: ('wagtail.blocks.StructBlock', [[('title', 22), ('image', 23), ('caption', 24)]], {}), 26: ('wagtail.embeds.blocks.EmbedBlock', (), {})}),
        ),
    ]
