# Generated by Django 5.0.11 on 2025-11-24 12:17

import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_alter_scorepage_content'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de publicación')),
                ('intro', models.CharField(blank=True, help_text='Breve descripción del test', max_length=250)),
                ('questions', wagtail.fields.StreamField([('question', 8)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Enunciado principal de la pregunta', 'max_length': 255}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Contexto o aclaraciones', 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Imagen opcional', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Texto de la respuesta', 'max_length': 255}), 4: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Marca esta casilla si la respuesta es correcta', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('text', 3), ('image', 2), ('is_correct', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'help_text': 'Cada pregunta debe tener exactamente 4 opciones', 'max_num': 4, 'min_num': 4}), 7: ('wagtail.blocks.TextBlock', (), {'help_text': 'Explicación que se mostrará al revelar la respuesta', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('prompt', 0), ('description', 1), ('illustration', 2), ('options', 6), ('explanation', 7)]], {})})),
                ('categories', modelcluster.fields.ParentalManyToManyField(blank=True, to='cms.musiccategory')),
                ('featured_image', models.ForeignKey(blank=True, help_text='Imagen destacada para la tarjeta del test', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('tags', modelcluster.fields.ParentalManyToManyField(blank=True, to='cms.musictag')),
            ],
            options={
                'verbose_name': 'Test Musical',
                'verbose_name_plural': 'Tests Musicales',
            },
            bases=('wagtailcore.page',),
        ),
    ]
