# Generated by Django 5.0.11 on 2025-12-15 00:00

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0011_testpage"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="HelpIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                "verbose_name": "Ayuda (Índice)",
                "verbose_name_plural": "Ayuda",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="HelpVideoPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro",
                    models.CharField(
                        blank=True,
                        help_text="Resumen corto del videotutorial",
                        max_length=250,
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        help_text="Enlace del vídeo (YouTube, Vimeo, etc.)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Videotutorial",
                "verbose_name_plural": "Videotutoriales",
            },
            bases=("wagtailcore.page",),
        ),
    ]
