# Generated by Django 5.0.11 on 2026-01-13 21:13

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


def migrate_categories_forward(apps, schema_editor):
    """Copiar relaciones M2M existentes al through model."""
    ScorePage = apps.get_model('cms', 'ScorePage')
    ScorePageCategory = apps.get_model('cms', 'ScorePageCategory')

    # Acceder a la tabla M2M antigua a través del campo categories
    # Django usa el through actual para acceder a las relaciones
    db_alias = schema_editor.connection.alias

    # Ejecutar query SQL directa para obtener las relaciones de la tabla antigua
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT scorepage_id, musiccategory_id
            FROM cms_scorepage_categories
        """)
        relations = cursor.fetchall()

    # Crear las relaciones en el through model con sort_order secuencial
    for i, (scorepage_id, category_id) in enumerate(relations):
        ScorePageCategory.objects.using(db_alias).create(
            score_page_id=scorepage_id,
            category_id=category_id,
            sort_order=i
        )


def migrate_categories_backward(apps, schema_editor):
    """Rollback: restaurar M2M directo."""
    # Eliminar todas las relaciones del through model
    ScorePageCategory = apps.get_model('cms', 'ScorePageCategory')
    ScorePageCategory.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_ensure_blogpage_m2m_tables'),
    ]

    operations = [
        # Paso 1: Crear el modelo through
        migrations.CreateModel(
            name='ScorePageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_scores', to='cms.musiccategory')),
                ('score_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_categories', to='cms.scorepage')),
            ],
            options={
                'verbose_name': 'Categoría de Partitura',
                'verbose_name_plural': 'Categorías de Partituras',
                'ordering': ['sort_order'],
                'unique_together': {('score_page', 'category')},
            },
        ),
        # Paso 2: Migrar datos existentes
        migrations.RunPython(migrate_categories_forward, migrate_categories_backward),
        # Paso 3: Eliminar el campo M2M antiguo
        migrations.RemoveField(
            model_name='scorepage',
            name='categories',
        ),
        # Paso 4: Recrear el campo con through model
        migrations.AddField(
            model_name='scorepage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, through='cms.ScorePageCategory', to='cms.musiccategory'),
        ),
    ]
