# Generated by Django 5.0.11 on 2026-01-14 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_scorepagecategory_alter_scorepage_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scorepagecategory',
            options={'ordering': ['sort_order'], 'verbose_name': 'Partitura', 'verbose_name_plural': 'Partituras'},
        ),
    ]
