# Generated by Django 5.0.11 on 2026-02-04 17:28

import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_alter_scorepagecategory_options'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictadoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de publicación')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Instrucciones del dictado o contexto para el estudiante')),
                ('content', wagtail.fields.StreamField([('audio', 3), ('answer_image', 8), ('answer_pdf', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': "Título del audio (ej: 'Dictado 1', 'Ejercicio rítmico')", 'max_length': 255}), 1: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Archivo de audio (MP3, WAV, OGG, etc.)'}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Descripción o instrucciones opcionales', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('audio_file', 1), ('description', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'Ver respuesta', 'help_text': 'Título del widget colapsable', 'max_length': 255}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Imagen de la respuesta'}), 6: ('wagtail.blocks.TextBlock', (), {'help_text': 'Pie de imagen opcional', 'required': False}), 7: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Si está marcado, la respuesta estará oculta por defecto', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('title', 4), ('image', 5), ('caption', 6), ('is_collapsed', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'default': 'Ver partitura', 'help_text': 'Título del widget colapsable', 'max_length': 255}), 10: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'PDF de la respuesta'}), 11: ('wagtail.blocks.TextBlock', (), {'help_text': 'Descripción opcional', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('title', 9), ('pdf', 10), ('description', 11), ('is_collapsed', 7)]], {})}, help_text='Añade audios y respuestas (imágenes o PDFs). Los audios se reproducen con WaveSurfer.js')),
                ('categories', modelcluster.fields.ParentalManyToManyField(blank=True, to='cms.musiccategory')),
                ('tags', modelcluster.fields.ParentalManyToManyField(blank=True, to='cms.musictag')),
            ],
            options={
                'verbose_name': 'Dictado',
                'verbose_name_plural': 'Dictados',
            },
            bases=('wagtailcore.page',),
        ),
    ]
