# Generated by Django 5.0.11 on 2026-03-17 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_dictadopage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedResourceFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('query_params', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_resource_filters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Filtro de Recurso Guardado',
                'verbose_name_plural': 'Filtros de Recursos Guardados',
                'ordering': ['name'],
            },
        ),
    ]
