# Generated by Django 5.0.11 on 2026-03-20 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0007_migrate_students_to_enrollments'),
        ('cms', '0018_savedresourcefilter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='moderator',
            field=models.ForeignKey(blank=True, help_text='Moderador del departamento que aprueba artículos', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_blogs', to=settings.AUTH_USER_MODEL, verbose_name='Encargado/a'),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Vincula este blog con una asignatura (hereda icono y color)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_indexes', to='clases.subject', verbose_name='Asignatura'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Marcar para mostrar en la portada del blog', verbose_name='Destacado'),
        ),
    ]
