# Generated by Django 5.0.11 on 2026-03-27 12:16

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_blog_featured_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='attachments',
            field=wagtail.fields.StreamField([('pdf_score', 4), ('audio', 7), ('image', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Título del PDF', 'max_length': 200}), 1: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Seleccionar archivo PDF'}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Descripción opcional', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Número de páginas', 'max_length': 10, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('pdf_file', 1), ('description', 2), ('page_count', 3)]], {'icon': 'doc-full-inverse', 'label': 'PDF'}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Título del audio', 'max_length': 200}), 6: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Seleccionar archivo audio'}), 7: ('wagtail.blocks.StructBlock', [[('title', 5), ('audio_file', 6), ('description', 2)]], {'icon': 'media', 'label': 'Audio'}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Título de la imagen', 'max_length': 200}), 9: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Seleccionar imagen'}), 10: ('wagtail.blocks.StructBlock', [[('title', 8), ('image', 9), ('caption', 2)]], {'icon': 'image', 'label': 'Image'})}, help_text='Archivos que se muestran como cards con descarga, visor y botón de librería', verbose_name='Archivos adjuntos'),
        ),
    ]
