# Generated by Django 5.0.11 on 2026-04-08 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_add_attachments_to_blogpage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='cover_image',
            field=models.ForeignKey(blank=True, help_text='Imagen de portada (usada cuando este índice actúa como libro en la biblioteca musical).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Portada'),
        ),
    ]
