# Generated by Django 5.0.11 on 2026-04-20 15:53

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_blogindexpage_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='🔗', help_text='Emoji o icono', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Enlace Externo',
                'verbose_name_plural': 'Enlaces Externos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='attachments',
            field=wagtail.fields.StreamField([('pdf_score', 4), ('audio', 7), ('image', 10), ('external_link', 13)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Título del PDF', 'max_length': 200}), 1: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Seleccionar archivo PDF'}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Descripción opcional', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Número de páginas', 'max_length': 10, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('pdf_file', 1), ('description', 2), ('page_count', 3)]], {'icon': 'doc-full-inverse', 'label': 'PDF'}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Título del audio', 'max_length': 200}), 6: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Seleccionar archivo audio'}), 7: ('wagtail.blocks.StructBlock', [[('title', 5), ('audio_file', 6), ('description', 2)]], {'icon': 'media', 'label': 'Audio'}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Título de la imagen', 'max_length': 200}), 9: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Seleccionar imagen'}), 10: ('wagtail.blocks.StructBlock', [[('title', 8), ('image', 9), ('caption', 2)]], {'icon': 'image', 'label': 'Image'}), 11: ('wagtail.snippets.blocks.SnippetChooserBlock', ('cms.ExternalResource',), {}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': 'Título alternativo (opcional)', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('resource', 11), ('override_title', 12)]], {'icon': 'link', 'label': 'Enlace Externo'})}, help_text='Archivos que se muestran como cards con descarga, visor y botón de librería', verbose_name='Archivos adjuntos'),
        ),
    ]
