# Generated by Django 5.0.11 on 2026-04-22 10:36

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_externalresource_alter_blogpage_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='attachments',
            field=wagtail.fields.StreamField([('pdf_score', 4), ('audio', 7), ('image', 10), ('video', 13), ('external_link', 16)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Título del PDF', 'max_length': 200}), 1: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Seleccionar archivo PDF'}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Descripción opcional', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Número de páginas', 'max_length': 10, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('pdf_file', 1), ('description', 2), ('page_count', 3)]], {'icon': 'doc-full-inverse', 'label': 'PDF'}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Título del audio', 'max_length': 200}), 6: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Seleccionar archivo audio'}), 7: ('wagtail.blocks.StructBlock', [[('title', 5), ('audio_file', 6), ('description', 2)]], {'icon': 'media', 'label': 'Audio'}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Título de la imagen', 'max_length': 200}), 9: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Seleccionar imagen'}), 10: ('wagtail.blocks.StructBlock', [[('title', 8), ('image', 9), ('caption', 2)]], {'icon': 'image', 'label': 'Image'}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'Título del vídeo', 'max_length': 200}), 12: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Seleccionar archivo de vídeo (máx. 10 MB)'}), 13: ('wagtail.blocks.StructBlock', [[('title', 11), ('video_file', 12), ('description', 2)]], {'icon': 'media', 'label': 'Vídeo'}), 14: ('wagtail.snippets.blocks.SnippetChooserBlock', ('cms.ExternalResource',), {}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': 'Título alternativo (opcional)', 'required': False}), 16: ('wagtail.blocks.StructBlock', [[('resource', 14), ('override_title', 15)]], {'icon': 'link', 'label': 'Enlace Externo'})}, help_text='Archivos que se muestran como cards con descarga, visor y botón de librería', verbose_name='Archivos adjuntos'),
        ),
    ]
