# Generated by Django 5.0.11 on 2026-04-28 15:25

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_add_video_block_to_blogpage'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailembeds', '0009_embed_cache_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggableEmbed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taggable', to='wagtailembeds.embed')),
            ],
            options={
                'verbose_name': 'Embed etiquetable',
                'verbose_name_plural': 'Embeds etiquetables',
            },
        ),
        migrations.CreateModel(
            name='TaggedEmbedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='cms.taggableembed')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='taggableembed',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='cms.TaggedEmbedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
