# Generated by Django 5.0.11 on 2026-05-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0025_alter_blogpage_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Solo el creador de la página puede verla. Las hijas heredan esta restricción.', verbose_name='Privada'),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='is_protected',
            field=models.BooleanField(default=False, help_text='Requiere iniciar sesión para ver esta página y sus hijas.', verbose_name='Protegida'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Solo el creador de la página puede verla.', verbose_name='Privada'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='is_protected',
            field=models.BooleanField(default=False, help_text='Requiere iniciar sesión para ver esta página.', verbose_name='Protegida'),
        ),
    ]
