# Generated by Django 5.0.11 on 2026-06-07 07:06

import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0026_add_protected_private_visibility'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlidesConAudioPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Descripcion breve')),
                ('slides', wagtail.fields.StreamField([('slide', 6)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Foto de la actuacion'}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Pie de foto opcional', 'required': False}), 2: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Grabacion de audio (MP3, WAV, OGG)'}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Titulo del audio', 'max_length': 255, 'required': False}), 4: ('wagtail.blocks.DecimalBlock', (), {'help_text': 'Segundo de inicio (vacio = desde el principio)', 'min_value': 0, 'required': False}), 5: ('wagtail.blocks.DecimalBlock', (), {'help_text': 'Segundo de fin (vacio = hasta el final)', 'min_value': 0, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 0), ('caption', 1), ('audio_file', 2), ('audio_title', 3), ('start_time', 4), ('end_time', 5)]], {})}, help_text='Anade slides: cada uno con una foto y un audio')),
            ],
            options={
                'verbose_name': 'Slides con Audio',
                'verbose_name_plural': 'Slides con Audio',
            },
            bases=('wagtailcore.page',),
        ),
    ]
