# Generated by Django 5.0.11 on 2026-08-22 12:25

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0027_slidesconaudiopage'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='cms.blogpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='blogpage',
            name='faceted_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='Vocabulario facetado (faceta:valor). Convive con las etiquetas de arriba mientras dura la migración.', through='cms.BlogPageTag', to='taggit.Tag', verbose_name='Etiquetas facetadas'),
        ),
        migrations.CreateModel(
            name='DictadoPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='cms.dictadopage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dictadopage',
            name='faceted_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='Vocabulario facetado (faceta:valor). Convive con las etiquetas de arriba mientras dura la migración.', through='cms.DictadoPageTag', to='taggit.Tag', verbose_name='Etiquetas facetadas'),
        ),
        migrations.CreateModel(
            name='ScorePageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='cms.scorepage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='scorepage',
            name='faceted_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='Vocabulario facetado (faceta:valor). Convive con las etiquetas de arriba mientras dura la migración.', through='cms.ScorePageTag', to='taggit.Tag', verbose_name='Etiquetas facetadas'),
        ),
        migrations.CreateModel(
            name='TestPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='cms.testpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='testpage',
            name='faceted_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='Vocabulario facetado (faceta:valor). Convive con las etiquetas de arriba mientras dura la migración.', through='cms.TestPageTag', to='taggit.Tag', verbose_name='Etiquetas facetadas'),
        ),
    ]
