# Generated by Django 5.0.11 on 2026-08-24 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0029_borrar_musictags_huerfanas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictadopage',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='scorepage',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='testpage',
            name='tags',
        ),
        migrations.DeleteModel(
            name='MusicTag',
        ),
    ]
