# Generated by Django 5.0.11 on 2026-08-27 10:42

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0030_remove_dictadopage_tags_remove_scorepage_tags_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibroDeEstudioPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='De que va este libro')),
                ('capitulos', wagtail.fields.StreamField([('pagina', 0)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Una pagina que ya existe. El orden manda.', 'page_type': ['cms.BlogPage', 'cms.ScorePage', 'cms.DictadoPage']})}, help_text='Arrastra para ordenar: este es el orden en que saldra a estudiar.', verbose_name='Capitulos')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Portada')),
            ],
            options={
                'verbose_name': 'Libro de estudio',
                'verbose_name_plural': 'Libros de estudio',
            },
            bases=('wagtailcore.page',),
        ),
    ]
