# Generated by Django 5.0.11 on 2026-08-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0031_librodeestudiopage'),
    ]

    operations = [
        migrations.AddField(
            model_name='librodeestudiopage',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Solo el creador de la página puede verla.', verbose_name='Privada'),
        ),
        migrations.AddField(
            model_name='librodeestudiopage',
            name='is_protected',
            field=models.BooleanField(default=False, help_text='Requiere iniciar sesión para ver esta página.', verbose_name='Protegida'),
        ),
    ]
