# Generated by Django 5.0.11 on 2026-08-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0032_librodeestudiopage_is_private_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='artist',
            field=models.CharField(blank=True, help_text='Quién la firma. ej: Fito & Fitipaldis', max_length=200, verbose_name='Artista / compositor'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='duration_minutes',
            field=models.CharField(blank=True, help_text='En minutos. ej: 3:24', max_length=10, verbose_name='Duración'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='key_signature',
            field=models.CharField(blank=True, help_text='ej: Em, C mayor, F# menor', max_length=20, verbose_name='Tonalidad'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='reference',
            field=models.CharField(blank=True, help_text='Número de catálogo, opus, o versión de referencia. ej: vers. Halestorm', max_length=200, verbose_name='Referencia'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='tempo',
            field=models.CharField(blank=True, help_text='BPM o indicación de tempo. ej: 117, Allegro', max_length=20, verbose_name='Tempo'),
        ),
    ]
