# Generated by Django 5.0.11 on 2026-08-29 08:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0033_blogpage_artist_blogpage_duration_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='key_signature',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='tempo',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='En segundos. La plantilla la pinta como m:ss.', null=True, verbose_name='Duración (segundos)'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='key_fifths',
            field=models.SmallIntegerField(blank=True, help_text='-7 a 7. Negativo bemoles, positivo sostenidos. 0 = Do mayor / La menor.', null=True, validators=[django.core.validators.MinValueValidator(-7), django.core.validators.MaxValueValidator(7)], verbose_name='Armadura (quintas)'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='key_mode',
            field=models.CharField(blank=True, choices=[('major', 'Mayor'), ('minor', 'Menor'), ('dorian', 'Dórico'), ('phrygian', 'Frigio'), ('lydian', 'Lidio'), ('mixolydian', 'Mixolidio'), ('aeolian', 'Eólico'), ('locrian', 'Locrio')], help_text='Valores de MusicXML. Los modales importan para el trabajo de improvisación.', max_length=12, verbose_name='Modo'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='tempo_bpm',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Pulsos por minuto. ej: 151', null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(400)], verbose_name='Tempo (BPM)'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='time_signature_beat_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (4, '4'), (8, '8'), (16, '16'), (32, '32')], help_text='El número de abajo. Potencia de dos, como exige el estándar.', null=True, verbose_name='Compás — denominador'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='time_signature_beats',
            field=models.PositiveSmallIntegerField(blank=True, help_text='El número de arriba. ej: 4 en 4/4, 6 en 6/8', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(64)], verbose_name='Compás — numerador'),
        ),
    ]
