# Generated by Django 5.0.11 on 2026-08-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0036_alter_blogpage_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='chordpro',
            field=models.TextField(blank=True, help_text='Formato ChordPro: los acordes entre corchetes justo antes de la sílaba en la que caen, p. ej. [Am]On the street where you [F]live. Directivas admitidas: {start_of_verse}, {end_of_verse}, {start_of_chorus}, {end_of_chorus}, {comment: ...}. No hace falta poner {title} ni {artist}: esos ya salen de la ficha.', verbose_name='Letra con acordes (ChordPro)'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='songsterr_url',
            field=models.URLField(blank=True, help_text='URL de la canción en Songsterr, para el botón sobre la tablatura. Si se deja vacío, el botón busca por artista y título.', max_length=500, verbose_name='Tablatura en Songsterr'),
        ),
    ]
