# Generated by Django 5.0.11 on 2026-09-17 09:24

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0038_remove_blogpage_categories_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpGuidePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.CharField(blank=True, help_text='De qué va la guía, en una línea', max_length=250)),
                ('resumen', wagtail.fields.RichTextField(blank=True, help_text='Contexto antes de los pasos: para qué sirve esto y cuándo usarlo')),
                ('pasos', wagtail.fields.StreamField([('paso', 4), ('aviso', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Qué se hace en este paso'}), 1: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Cómo se hace'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'La pantalla en ese momento', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Qué mirar en la captura', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('titulo', 0), ('texto', 1), ('captura', 2), ('pie', 3)]], {'icon': 'list-ol', 'label': 'Paso'}), 5: ('wagtail.blocks.RichTextBlock', (), {}), 6: ('wagtail.blocks.StructBlock', [[('texto', 5)]], {'icon': 'warning', 'label': 'Aviso'})}, help_text='Arrastra para reordenar. La numeración sale sola.', verbose_name='Pasos')),
            ],
            options={
                'verbose_name': 'Guía de ayuda',
                'verbose_name_plural': 'Guías de ayuda',
            },
            bases=('wagtailcore.page',),
        ),
    ]
