# Generated by Django 5.0.11 on 2026-09-04 06:35

import cms.adjuntos
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictadoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de publicación')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Instrucciones del dictado o contexto para el estudiante')),
                ('content', wagtail.fields.StreamField([('audio', 3), ('answer_image', 8), ('answer_pdf', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': "Título del audio (ej: 'Dictado 1', 'Ejercicio rítmico')", 'max_length': 255}), 1: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Archivo de audio (MP3, WAV, OGG, etc.)'}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Descripción o instrucciones opcionales', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('audio_file', 1), ('description', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'Ver respuesta', 'help_text': 'Título del widget colapsable', 'max_length': 255}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Imagen de la respuesta'}), 6: ('wagtail.blocks.TextBlock', (), {'help_text': 'Pie de imagen opcional', 'required': False}), 7: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Si está marcado, la respuesta estará oculta por defecto', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('title', 4), ('image', 5), ('caption', 6), ('is_collapsed', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'default': 'Ver partitura', 'help_text': 'Título del widget colapsable', 'max_length': 255}), 10: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'PDF de la respuesta'}), 11: ('wagtail.blocks.TextBlock', (), {'help_text': 'Descripción opcional', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('title', 9), ('pdf', 10), ('description', 11), ('is_collapsed', 7)]], {})}, help_text='Añade audios y respuestas (imágenes o PDFs). Los audios se reproducen con WaveSurfer.js')),
            ],
            options={
                'verbose_name': 'Dictado',
                'verbose_name_plural': 'Dictados',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MusicComposer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('birth_year', models.PositiveIntegerField(blank=True, null=True)),
                ('death_year', models.PositiveIntegerField(blank=True, null=True)),
                ('bio', wagtail.fields.RichTextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Compositor Musical',
                'verbose_name_plural': 'Compositores Musicales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MusicLibraryIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Texto de introducción para la biblioteca musical')),
            ],
            options={
                'verbose_name': 'Biblioteca Musical',
                'verbose_name_plural': 'Bibliotecas Musicales',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SetlistPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.fields.RichTextField(blank=True, help_text='Descripción de este setlist')),
                ('setlist_items', wagtail.fields.StreamField([('score_reference', 0), ('notes', 1), ('separator', 3)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Seleccionar una partitura de tu biblioteca', 'page_type': ['musica.ScorePage']}), 1: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Notas para este elemento del setlist'}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': "Título de sección (ej: 'Intermedio')", 'max_length': 100}), 3: ('wagtail.blocks.StructBlock', [[('title', 2)]], {'icon': 'horizontalrule'})})),
            ],
            options={
                'verbose_name': 'Lista de Reproducción',
                'verbose_name_plural': 'Listas de Reproducción',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SlidesConAudioPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Descripcion breve')),
                ('slides', wagtail.fields.StreamField([('slide', 6)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Foto de la actuacion'}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Pie de foto opcional', 'required': False}), 2: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Grabacion de audio (MP3, WAV, OGG)'}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Titulo del audio', 'max_length': 255, 'required': False}), 4: ('wagtail.blocks.DecimalBlock', (), {'help_text': 'Segundo de inicio (vacio = desde el principio)', 'min_value': 0, 'required': False}), 5: ('wagtail.blocks.DecimalBlock', (), {'help_text': 'Segundo de fin (vacio = hasta el final)', 'min_value': 0, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 0), ('caption', 1), ('audio_file', 2), ('audio_title', 3), ('start_time', 4), ('end_time', 5)]], {})}, help_text='Anade slides: cada uno con una foto y un audio')),
            ],
            options={
                'verbose_name': 'Slides con Audio',
                'verbose_name_plural': 'Slides con Audio',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='DictadoPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='musica.dictadopage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dictadopage',
            name='faceted_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='Vocabulario facetado (faceta:valor). Convive con las etiquetas de arriba mientras dura la migración.', through='musica.DictadoPageTag', to='taggit.Tag', verbose_name='Etiquetas facetadas'),
        ),
        migrations.CreateModel(
            name='LibroDeEstudioPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='De que va este libro')),
                ('capitulos', wagtail.fields.StreamField([('pagina', 0)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Una pagina que ya existe. El orden manda.', 'page_type': ['musica.RecursoPage', 'musica.ScorePage', 'musica.DictadoPage']})}, help_text='Arrastra para ordenar: este es el orden en que saldra a estudiar.', verbose_name='Capitulos')),
                ('is_protected', models.BooleanField(default=False, help_text='Requiere iniciar sesión para ver esta página.', verbose_name='Protegida')),
                ('is_private', models.BooleanField(default=False, help_text='Solo el creador de la página puede verla.', verbose_name='Privada')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Portada')),
            ],
            options={
                'verbose_name': 'Libro de estudio',
                'verbose_name_plural': 'Libros de estudio',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='LibroPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('is_protected', models.BooleanField(default=False, help_text='Requiere iniciar sesión para ver este libro y sus capítulos.', verbose_name='Protegida')),
                ('is_private', models.BooleanField(default=False, help_text='Solo el creador puede verlo. Los capítulos heredan la restricción.', verbose_name='Privada')),
                ('cover_image', models.ForeignKey(blank=True, help_text='Imagen de portada del libro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Portada')),
            ],
            options={
                'verbose_name': 'Libro de la biblioteca',
                'verbose_name_plural': 'Libros de la biblioteca',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MusicCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Clase CSS del icono', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='musica.musiccategory')),
            ],
            options={
                'verbose_name': 'Categoría Musical',
                'verbose_name_plural': 'Categorías Musicales',
                'ordering': ['name'],
                'unique_together': {('name', 'parent')},
            },
        ),
        migrations.AddField(
            model_name='dictadopage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='musica.musiccategory'),
        ),
        migrations.CreateModel(
            name='RecursoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(verbose_name='Fecha de publicación')),
                ('intro', models.CharField(help_text='Resumen del artículo', max_length=250)),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Marcar para mostrar en la portada del blog', verbose_name='Destacado')),
                ('is_protected', models.BooleanField(default=False, help_text='Requiere iniciar sesión para ver esta página.', verbose_name='Protegida')),
                ('is_private', models.BooleanField(default=False, help_text='Solo el creador de la página puede verla.', verbose_name='Privada')),
                ('attachments', wagtail.fields.StreamField([('pdf_score', 1), ('audio', 3), ('image', 6), ('video', 8), ('external_link', 11)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Seleccionar un PDF o un archivo Guitar Pro (.gp, .gp3, .gp4, .gp5, .gpx)'}), 1: ('wagtail.blocks.StructBlock', [[('pdf_file', 0)]], {'icon': 'doc-full-inverse', 'label': 'PDF / Guitar Pro'}), 2: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Seleccionar archivo audio'}), 3: ('wagtail.blocks.StructBlock', [[('audio_file', 2)]], {'icon': 'media', 'label': 'Audio'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Seleccionar imagen'}), 5: ('wagtail.blocks.TextBlock', (), {'help_text': 'Descripción opcional', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5)]], {'icon': 'image', 'label': 'Imagen'}), 7: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Seleccionar vídeo (máx. 10 MB)'}), 8: ('wagtail.blocks.StructBlock', [[('video_file', 7)]], {'icon': 'media', 'label': 'Vídeo'}), 9: ('wagtail.snippets.blocks.SnippetChooserBlock', ('cms.ExternalResource',), {}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Título alternativo (opcional)', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('resource', 9), ('override_title', 10)]], {'icon': 'link', 'label': 'Enlace'})}, help_text='Archivos que se muestran como cards con descarga, visor y botón de librería', verbose_name='Archivos adjuntos')),
                ('artist', models.CharField(blank=True, help_text='Quién la firma. ej: Fito & Fitipaldis', max_length=200, verbose_name='Artista / compositor')),
                ('key_fifths', models.SmallIntegerField(blank=True, help_text='-7 a 7. Negativo bemoles, positivo sostenidos. 0 = Do mayor / La menor.', null=True, validators=[django.core.validators.MinValueValidator(-7), django.core.validators.MaxValueValidator(7)], verbose_name='Armadura (quintas)')),
                ('key_mode', models.CharField(blank=True, choices=[('major', 'Mayor'), ('minor', 'Menor'), ('dorian', 'Dórico'), ('phrygian', 'Frigio'), ('lydian', 'Lidio'), ('mixolydian', 'Mixolidio'), ('aeolian', 'Eólico'), ('locrian', 'Locrio')], help_text='Valores de MusicXML. Los modales importan para el trabajo de improvisación.', max_length=12, verbose_name='Modo')),
                ('time_signature_beats', models.PositiveSmallIntegerField(blank=True, help_text='El número de arriba. ej: 4 en 4/4, 6 en 6/8', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(64)], verbose_name='Compás — numerador')),
                ('time_signature_beat_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (4, '4'), (8, '8'), (16, '16'), (32, '32')], help_text='El número de abajo. Potencia de dos, como exige el estándar.', null=True, verbose_name='Compás — denominador')),
                ('tempo_bpm', models.PositiveSmallIntegerField(blank=True, help_text='Pulsos por minuto. ej: 151', null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(400)], verbose_name='Tempo (BPM)')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='En segundos. La plantilla la pinta como m:ss.', null=True, verbose_name='Duración (segundos)')),
                ('reference', models.CharField(blank=True, help_text='Número de catálogo, opus, o versión de referencia. ej: vers. Halestorm', max_length=200, verbose_name='Referencia')),
                ('songsterr_url', models.URLField(blank=True, help_text='URL de la canción en Songsterr, para el botón sobre la tablatura. Si se deja vacío, el botón busca por artista y título.', max_length=500, verbose_name='Tablatura en Songsterr')),
                ('chordpro', models.TextField(blank=True, help_text='Formato ChordPro: los acordes entre corchetes justo antes de la sílaba en la que caen, p. ej. [Am]On the street where you [F]live. Directivas admitidas: {start_of_verse}, {end_of_verse}, {start_of_chorus}, {end_of_chorus}, {comment: ...}. No hace falta poner {title} ni {artist}: esos ya salen de la ficha.', verbose_name='Letra con acordes (ChordPro)')),
                ('categories', modelcluster.fields.ParentalManyToManyField(blank=True, to='musica.musiccategory')),
                ('featured_image', models.ForeignKey(blank=True, help_text='Imagen destacada del artículo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Recurso musical',
                'verbose_name_plural': 'Recursos musicales',
            },
            bases=(cms.adjuntos.AdjuntosMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='RecursoPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='musica.recursopage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='recursopage',
            name='faceted_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='Vocabulario facetado (faceta:valor).', through='musica.RecursoPageTag', to='taggit.Tag', verbose_name='Etiquetas facetadas'),
        ),
        migrations.CreateModel(
            name='ScorePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content', wagtail.fields.StreamField([('pdf_score', 4), ('metadata', 11), ('bookmarks', 17), ('notes', 18), ('audio', 21), ('image', 25), ('url', 28), ('embed', 29)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Título del PDF', 'max_length': 200}), 1: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Seleccionar archivo PDF'}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Descripción opcional', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Número de páginas', 'max_length': 10, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('pdf_file', 1), ('description', 2), ('page_count', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'ej: C mayor, F# menor', 'max_length': 20, 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'BPM o indicación de tempo', 'max_length': 20, 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Principiante, Fácil, Intermedio, Avanzado, Experto', 'max_length': 20, 'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 10, 'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Número de catálogo, opus, etc.', 'max_length': 200, 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('composer', 5), ('key_signature', 6), ('tempo', 7), ('difficulty', 8), ('duration_minutes', 9), ('reference', 10)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': "Número de página o rango (ej: '5' o '5-8')", 'max_length': 10}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': "Tipo: 'page' para página única, 'item' para rango de páginas", 'max_length': 10}), 15: ('wagtail.blocks.TextBlock', (), {'required': False}), 16: ('wagtail.blocks.StructBlock', [[('title', 12), ('page_number', 13), ('bookmark_type', 14), ('notes', 15)]], {}), 17: ('wagtail.blocks.ListBlock', (16,), {}), 18: ('wagtail.blocks.RichTextBlock', (), {}), 19: ('wagtail.blocks.CharBlock', (), {'help_text': 'Título del audio', 'max_length': 200}), 20: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Seleccionar archivo audio'}), 21: ('wagtail.blocks.StructBlock', [[('title', 19), ('audio_file', 20), ('description', 2)]], {}), 22: ('wagtail.blocks.CharBlock', (), {'help_text': 'Título de la imagen', 'max_length': 200}), 23: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Seleccionar imagen'}), 24: ('wagtail.blocks.TextBlock', (), {'help_text': 'Texto alternativo para accesibilidad', 'required': False}), 25: ('wagtail.blocks.StructBlock', [[('title', 22), ('image', 23), ('caption', 24)]], {}), 26: ('wagtail.blocks.CharBlock', (), {'help_text': 'Título del enlace', 'max_length': 200}), 27: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL'}), 28: ('wagtail.blocks.StructBlock', [[('title', 26), ('url', 27)]], {}), 29: ('wagtail.embeds.blocks.EmbedBlock', (), {})})),
                ('composer', models.ForeignKey(blank=True, help_text='Seleccionar o añadir un compositor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='musica.musiccomposer')),
            ],
            options={
                'verbose_name': 'Partitura',
                'verbose_name_plural': 'Partituras',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ScorePageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_scores', to='musica.musiccategory')),
                ('score_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_categories', to='musica.scorepage')),
            ],
            options={
                'verbose_name': 'Partitura',
                'verbose_name_plural': 'Partituras',
                'ordering': ['sort_order'],
                'unique_together': {('score_page', 'category')},
            },
        ),
        migrations.AddField(
            model_name='scorepage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, through='musica.ScorePageCategory', to='musica.musiccategory'),
        ),
        migrations.CreateModel(
            name='ScorePageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='musica.scorepage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='scorepage',
            name='faceted_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='Vocabulario facetado (faceta:valor). Convive con las etiquetas de arriba mientras dura la migración.', through='musica.ScorePageTag', to='taggit.Tag', verbose_name='Etiquetas facetadas'),
        ),
        migrations.CreateModel(
            name='TestPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de publicación')),
                ('intro', models.CharField(blank=True, help_text='Breve descripción del test', max_length=250)),
                ('questions', wagtail.fields.StreamField([('question', 8)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Enunciado principal de la pregunta', 'max_length': 255}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Contexto o aclaraciones', 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Imagen opcional', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Texto de la respuesta', 'max_length': 255}), 4: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Marca esta casilla si la respuesta es correcta', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('text', 3), ('image', 2), ('is_correct', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'help_text': 'Cada pregunta debe tener exactamente 4 opciones', 'max_num': 4, 'min_num': 4}), 7: ('wagtail.blocks.TextBlock', (), {'help_text': 'Explicación que se mostrará al revelar la respuesta', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('prompt', 0), ('description', 1), ('illustration', 2), ('options', 6), ('explanation', 7)]], {})})),
                ('categories', modelcluster.fields.ParentalManyToManyField(blank=True, to='musica.musiccategory')),
                ('featured_image', models.ForeignKey(blank=True, help_text='Imagen destacada para la tarjeta del test', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Test Musical',
                'verbose_name_plural': 'Tests Musicales',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TestPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='musica.testpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='testpage',
            name='faceted_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='Vocabulario facetado (faceta:valor). Convive con las etiquetas de arriba mientras dura la migración.', through='musica.TestPageTag', to='taggit.Tag', verbose_name='Etiquetas facetadas'),
        ),
    ]
