# Generated by Django 5.0.11 on 2026-09-09 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0003_limpiar_referencias_muertas'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnlaceExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('proveedor', models.CharField(choices=[('blink', 'Blink Learning')], default='blink', max_length=20, verbose_name='Proveedor')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('source_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enlaces_externos', to='wagtailcore.page', verbose_name='Capítulo')),
            ],
            options={
                'verbose_name': 'Enlace externo',
                'verbose_name_plural': 'Enlaces externos',
                'ordering': ['source_page', 'orden', 'pk'],
                'unique_together': {('source_page', 'url')},
            },
        ),
    ]
