# Generated by Django 5.0.11 on 2026-09-15 17:26

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0004_enlaceexterno'),
    ]

    operations = [
        migrations.AddField(
            model_name='recursopage',
            name='idioma',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='es', help_text='En qué lengua están la entradilla y el cuerpo de esta ficha.', max_length=5, verbose_name='Lengua del texto'),
        ),
        migrations.CreateModel(
            name='RecursoTraduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('idioma', models.CharField(choices=[('es', 'Español'), ('en', 'English')], max_length=5, verbose_name='Lengua')),
                ('intro', models.CharField(help_text='Resumen del artículo en esta lengua. Es lo que se lee bajo el título.', max_length=250, verbose_name='Entradilla')),
                ('body', wagtail.fields.RichTextField(blank=True, verbose_name='Cuerpo')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='traducciones', to='musica.recursopage')),
            ],
            options={
                'verbose_name': 'Traducción',
                'verbose_name_plural': 'Traducciones',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='recursotraduccion',
            constraint=models.UniqueConstraint(fields=('page', 'idioma'), name='musica_recurso_una_traduccion_por_lengua'),
        ),
    ]
