# Generated by Django 5.0.11 on 2026-09-16 17:06

import django.core.validators
import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0005_recursopage_idioma_recursotraduccion_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Cómo lo llamas: "Sailing Boat", "Allemande", "el ejercicio de terceras"', max_length=200, verbose_name='Nombre')),
                ('pagina_desde', models.PositiveSmallIntegerField(default=1, help_text='Número de página dentro del PDF, empezando por 1', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Página desde')),
                ('pagina_hasta', models.PositiveSmallIntegerField(blank=True, help_text='Vacío = una sola página', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Página hasta')),
                ('pagina_offset_impresa', models.SmallIntegerField(blank=True, help_text='Cuánto hay que restar al índice del PDF para obtener el número impreso. Si la página 14 del PDF es la 10 del libro, pon 4.', null=True, verbose_name='Desfase de numeración')),
                ('rect_x0', models.FloatField(blank=True, null=True, verbose_name='Recorte — izquierda')),
                ('rect_y0', models.FloatField(blank=True, null=True, verbose_name='Recorte — arriba')),
                ('rect_x1', models.FloatField(blank=True, null=True, verbose_name='Recorte — derecha')),
                ('rect_y1', models.FloatField(blank=True, null=True, verbose_name='Recorte — abajo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('documento', models.ForeignKey(help_text='El documento del que se recorta. No se modifica nunca.', on_delete=django.db.models.deletion.PROTECT, related_name='recortes', to='wagtaildocs.document', verbose_name='PDF de origen')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='Etiquetas propias del recorte. No las hereda del PDF.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Recorte',
                'verbose_name_plural': 'Recortes',
                'ordering': ['documento', 'pagina_desde', 'nombre'],
                'indexes': [models.Index(fields=['documento', 'pagina_desde'], name='musica_reco_documen_e57032_idx')],
            },
        ),
    ]
