# Generated by Django 5.0.11 on 2026-09-16 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0007_alter_librodeestudiopage_capitulos_and_more'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoRestringido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solo_por_recorte', models.BooleanField(default=True, help_text='Marcado: el PDF completo deja de servirse por su URL.', verbose_name='Solo por recorte')),
                ('motivo', models.CharField(blank=True, help_text='Para acordarse dentro de un año. ej: método comercial con licencia de aula', max_length=200, verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('documento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restriccion', to='wagtaildocs.document', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Documento restringido',
                'verbose_name_plural': 'Documentos restringidos',
            },
        ),
    ]
