# Generated by Django 5.0.11 on 2026-09-25 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0008_documentorestringido'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetraConAcordes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='letra_con_acordes', to='musica.recursopage', verbose_name='Canción')),
            ],
            options={
                'verbose_name': 'Letra con acordes',
                'verbose_name_plural': 'Letras con acordes',
            },
        ),
    ]
