# Generated by Django 5.0.11 on 2026-10-01 13:28

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0009_letraconacordes'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibroDeEstudioPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='musica.librodeestudiopage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='librodeestudiopage',
            name='faceted_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='Las heredan todos los elementos de la biblioteca que salen de este libro: etiquetar aquí «concepto:caged» vale por etiquetar cada capítulo.', through='musica.LibroDeEstudioPageTag', to='taggit.Tag', verbose_name='Etiquetas facetadas'),
        ),
        migrations.CreateModel(
            name='LibroPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='musica.libropage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='libropage',
            name='faceted_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='Las heredan todos los elementos de la biblioteca que salen de este libro: etiquetar aquí «concepto:caged» vale por etiquetar cada capítulo.', through='musica.LibroPageTag', to='taggit.Tag', verbose_name='Etiquetas facetadas'),
        ),
    ]
