# Generated by Django 5.0.11 on 2026-09-25 11:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Libreta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Libreta de música', max_length=120)),
                ('subtitulo', models.CharField(blank=True, help_text='El curso, por ejemplo «4º ESO».', max_length=120)),
                ('portada', models.BooleanField(default=True)),
                ('indice', models.BooleanField(default=True)),
                ('primera_pagina', models.PositiveIntegerField(default=1, help_text='Número que lleva la primera página del PDF, sea portada u hoja.', validators=[django.core.validators.MinValueValidator(1)])),
                ('hoja_nueva_por_seccion', models.BooleanField(default=True, help_text='A doble cara, cada elemento empieza en hoja nueva (se rellena con una página en blanco).')),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libretas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-actualizada'],
            },
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('titulo', models.CharField(max_length=120)),
                ('copias', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('texto', models.TextField(blank=True)),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.document')),
                ('imagen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('libreta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementos', to='libreta.libreta')),
            ],
            options={
                'ordering': ['orden', 'pk'],
            },
        ),
    ]
