# Generated by Django 5.0.11 on 2026-09-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemento',
            name='plantilla',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
