# Generated by Django 5.0.11 on 2026-09-25 19:03

from django.db import migrations, models


def apagar_el_relleno(apps, schema_editor):
    """Las libretas que ya existen también pasan a sin relleno: el valor
    anterior metía páginas en blanco que nadie había pedido."""
    Libreta = apps.get_model("libreta", "Libreta")
    Libreta.objects.filter(hoja_nueva_por_seccion=True).update(hoja_nueva_por_seccion=False)


class Migration(migrations.Migration):

    dependencies = [
        ('libreta', '0002_elemento_plantilla'),
    ]

    operations = [
        migrations.RunPython(apagar_el_relleno, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='libreta',
            name='hoja_nueva_por_seccion',
            field=models.BooleanField(default=False, help_text='A doble cara, cada elemento empieza en hoja nueva (se rellena con una página en blanco).'),
        ),
    ]
