# Generated by Django 5.0.11 on 2026-09-04 06:35

import cms.adjuntos
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clases', '0013_classsession_reflection'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(verbose_name='Fecha de publicación')),
                ('intro', models.CharField(help_text='Resumen del artículo', max_length=250)),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Marcar para mostrar en la portada del blog', verbose_name='Destacado')),
                ('is_protected', models.BooleanField(default=False, help_text='Requiere iniciar sesión para ver esta página.', verbose_name='Protegida')),
                ('is_private', models.BooleanField(default=False, help_text='Solo el creador de la página puede verla.', verbose_name='Privada')),
                ('attachments', wagtail.fields.StreamField([('pdf_score', 1), ('audio', 3), ('image', 6), ('video', 8), ('external_link', 11)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Seleccionar un PDF o un archivo Guitar Pro (.gp, .gp3, .gp4, .gp5, .gpx)'}), 1: ('wagtail.blocks.StructBlock', [[('pdf_file', 0)]], {'icon': 'doc-full-inverse', 'label': 'PDF / Guitar Pro'}), 2: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Seleccionar archivo audio'}), 3: ('wagtail.blocks.StructBlock', [[('audio_file', 2)]], {'icon': 'media', 'label': 'Audio'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Seleccionar imagen'}), 5: ('wagtail.blocks.TextBlock', (), {'help_text': 'Descripción opcional', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5)]], {'icon': 'image', 'label': 'Imagen'}), 7: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Seleccionar vídeo (máx. 10 MB)'}), 8: ('wagtail.blocks.StructBlock', [[('video_file', 7)]], {'icon': 'media', 'label': 'Vídeo'}), 9: ('wagtail.snippets.blocks.SnippetChooserBlock', ('cms.ExternalResource',), {}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Título alternativo (opcional)', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('resource', 9), ('override_title', 10)]], {'icon': 'link', 'label': 'Enlace'})}, help_text='Archivos que se muestran como cards con descarga, visor y botón de librería', verbose_name='Archivos adjuntos')),
                ('featured_image', models.ForeignKey(blank=True, help_text='Imagen destacada del artículo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Artículo de departamento',
                'verbose_name_plural': 'Artículos de departamento',
            },
            bases=(cms.adjuntos.AdjuntosMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='ArticuloPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='blogs.articulopage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='articulopage',
            name='faceted_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='Vocabulario facetado (faceta:valor).', through='blogs.ArticuloPageTag', to='taggit.Tag', verbose_name='Etiquetas'),
        ),
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('is_protected', models.BooleanField(default=False, help_text='Requiere iniciar sesión para ver esta página y sus hijas.', verbose_name='Protegida')),
                ('is_private', models.BooleanField(default=False, help_text='Solo el creador de la página puede verla. Las hijas heredan esta restricción.', verbose_name='Privada')),
                ('cover_image', models.ForeignKey(blank=True, help_text='Imagen de portada del departamento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Portada')),
                ('moderator', models.ForeignKey(blank=True, help_text='Moderador del departamento que aprueba artículos', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_blogs', to=settings.AUTH_USER_MODEL, verbose_name='Encargado/a')),
                ('subject', models.ForeignKey(blank=True, help_text='Vincula este blog con una asignatura (hereda icono y color)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_indexes', to='clases.subject', verbose_name='Asignatura')),
            ],
            options={
                'verbose_name': 'Blog de departamento',
                'verbose_name_plural': 'Blogs de departamento',
            },
            bases=('wagtailcore.page',),
        ),
    ]
