# Generated by Django 5.0.11 on 2026-09-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulopage',
            name='source_url',
            field=models.URLField(blank=True, default='', editable=False, help_text='Permalink del post original, si el artículo se importó.', max_length=500, verbose_name='URL de origen'),
        ),
    ]
