# Generated by Django 5.0.11 on 2026-09-27 15:47

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_articulopage_is_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulopage',
            name='attachments',
            field=wagtail.fields.StreamField([('pdf_score', 1), ('audio', 3), ('image', 6), ('video', 8), ('external_link', 11)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Un PDF u otro documento para descargar', 'label': 'Archivo'}), 1: ('wagtail.blocks.StructBlock', [[('pdf_file', 0)]], {'icon': 'doc-full-inverse', 'label': 'Documento'}), 2: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Seleccionar archivo audio'}), 3: ('wagtail.blocks.StructBlock', [[('audio_file', 2)]], {'icon': 'media', 'label': 'Audio'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Seleccionar imagen'}), 5: ('wagtail.blocks.TextBlock', (), {'help_text': 'Descripción opcional', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5)]], {'icon': 'image', 'label': 'Imagen'}), 7: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Seleccionar vídeo (máx. 10 MB)'}), 8: ('wagtail.blocks.StructBlock', [[('video_file', 7)]], {'icon': 'media', 'label': 'Vídeo'}), 9: ('wagtail.snippets.blocks.SnippetChooserBlock', ('cms.ExternalResource',), {}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Título alternativo (opcional)', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('resource', 9), ('override_title', 10)]], {'icon': 'link', 'label': 'Enlace'})}, help_text='Documentos para descargar, audios y vídeos. Se muestran al final del artículo, en ese orden.', verbose_name='Archivos adjuntos'),
        ),
    ]
