# Generated by Django 5.0.11 on 2025-11-10 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('last_viewed', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notas personales sobre este elemento')),
                ('favorite', models.BooleanField(default=False)),
                ('times_viewed', models.PositiveIntegerField(default=0)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item de Biblioteca',
                'verbose_name_plural': 'Items de Biblioteca',
                'ordering': ['-added_at'],
                'indexes': [models.Index(fields=['user', '-added_at'], name='my_library__user_id_78cb57_idx'), models.Index(fields=['content_type', 'object_id'], name='my_library__content_8930a2_idx')],
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
    ]
