# Generated by Django 5.0.11 on 2025-11-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libraryitem',
            options={'ordering': ['proficiency_level', 'times_viewed', '-added_at'], 'verbose_name': 'Item de Biblioteca', 'verbose_name_plural': 'Items de Biblioteca'},
        ),
        migrations.AddField(
            model_name='libraryitem',
            name='proficiency_level',
            field=models.PositiveSmallIntegerField(choices=[(1, '⭐ Apenas lo conozco'), (2, '⭐⭐ Lo estoy aprendiendo'), (3, '⭐⭐⭐ Lo conozco bien'), (4, '⭐⭐⭐⭐ Me lo sé muy bien')], default=1, help_text='Nivel de dominio de este contenido (1-4)'),
        ),
    ]
