# Generated by Django 5.0.11 on 2026-04-15 11:43

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_library', '0003_libraryitem_source_page'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryitem',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Tags para items sin tags propios (embeds)', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
