# Generated by Django 5.0.11 on 2026-08-11 22:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_library', '0005_librarydeck'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('session_uuid', models.UUIDField(blank=True, db_index=True, help_text='Agrupa los repasos de una misma sesión', null=True)),
                ('source', models.CharField(choices=[('study', 'Sesión de estudio'), ('manual', 'Valoración manual')], default='study', help_text="Dónde ocurrió el repaso — 'manual' no es práctica real", max_length=16)),
                ('proficiency_before', models.PositiveSmallIntegerField(blank=True, help_text='Nivel antes de este repaso', null=True)),
                ('proficiency_after', models.PositiveSmallIntegerField(blank=True, help_text='Nivel declarado en este repaso', null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Tiempo dedicado al item', null=True)),
                ('deck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='my_library.librarydeck', verbose_name='Mazo de origen')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='my_library.libraryitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Repaso',
                'verbose_name_plural': 'Repasos',
                'ordering': ['-reviewed_at'],
                'indexes': [models.Index(fields=['user', '-reviewed_at'], name='my_library__user_id_dd0cd5_idx'), models.Index(fields=['item', '-reviewed_at'], name='my_library__item_id_7fdbd0_idx')],
            },
        ),
    ]
