# Generated by Django 5.0.11 on 2026-08-12 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_library', '0007_sharednote'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('nombre', models.CharField(help_text='Cómo lo llamas: "compases 30-60", "el estribillo"', max_length=200)),
                ('pagina_desde', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pagina_hasta', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('segundo_desde', models.PositiveIntegerField(blank=True, null=True)),
                ('segundo_hasta', models.PositiveIntegerField(blank=True, null=True)),
                ('proficiency_level', models.PositiveSmallIntegerField(default=1, help_text='Nivel de dominio de ESTA sección')),
                ('notes', models.TextField(blank=True, help_text='Notas de esta sección')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='my_library.libraryitem')),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
                'ordering': ['orden', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='reviewlog',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='my_library.itemsection'),
        ),
        migrations.AddIndex(
            model_name='itemsection',
            index=models.Index(fields=['item', 'orden'], name='my_library__item_id_a99721_idx'),
        ),
    ]
