# Generated by Django 5.0.11 on 2026-08-24 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_library', '0009_arrastrar_mazos_al_vocabulario_facetado'),
        # `makemigrations` fija por defecto la ÚLTIMA migración de wagtailcore
        # que tenga instalada la máquina donde se genera. Aquí eso rompió el
        # despliegue: local corría Wagtail 7.3.3 y producción 7.3.1, que no
        # tiene la 0097, así que `migrate` abortó con NodeNotFoundError y la
        # tabla no se creó — con el código nuevo ya arriba y las páginas de
        # libro dando 500.
        #
        # Para una clave ajena a `Page` basta con que Page exista, y eso pasa en
        # la 0001. Anclar ahí hace la migración independiente de la versión de
        # Wagtail de cada entorno.
        ('wagtailcore', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryitem',
            name='descartado',
            field=models.BooleanField(default=False, verbose_name='Descartado'),
        ),
        migrations.CreateModel(
            name='LibraryGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_goals', to='wagtailcore.page', verbose_name='Libro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Objetivo de biblioteca',
                'verbose_name_plural': 'Objetivos de biblioteca',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'libro')},
            },
        ),
    ]
