# Generated by Django 5.0.11 on 2026-08-24 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_library', '0009_arrastrar_mazos_al_vocabulario_facetado'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryitem',
            name='descartado',
            field=models.BooleanField(default=False, verbose_name='Descartado'),
        ),
        migrations.CreateModel(
            name='LibraryGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_goals', to='wagtailcore.page', verbose_name='Libro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Objetivo de biblioteca',
                'verbose_name_plural': 'Objetivos de biblioteca',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'libro')},
            },
        ),
    ]
