# Generated by Django 5.0.11 on 2026-08-27 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_library', '0010_libraryitem_descartado_librarygoal'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryitem',
            name='libro',
            field=models.ForeignKey(blank=True, help_text='Solo para libros que agrupan páginas por referencia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_items_del_libro', to='wagtailcore.page', verbose_name='Libro de origen'),
        ),
        migrations.AddField(
            model_name='libraryitem',
            name='orden',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden en el libro'),
        ),
    ]
