# Generated by Django 5.0.11 on 2026-09-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_library', '0012_orden_de_los_elementos_en_su_libro'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarygoal',
            name='ultima_novedad',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última vez que aportó novedad'),
        ),
    ]
