# Generated by Django 5.0.11 on 2025-09-24 11:43

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('music_cards', '0017_alter_musicitem_options_musicitem_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_type', models.CharField(choices=[('individual', 'Estudio Individual'), ('class', 'Clase Grupal'), ('homework', 'Tarea Asignada'), ('practice', 'Práctica Libre')], max_length=20)),
                ('name', models.CharField(help_text='Nombre descriptivo del contexto', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('initial_interval', models.DurationField(default=datetime.timedelta(days=1), help_text='Intervalo inicial entre repasos')),
                ('max_interval', models.DurationField(default=datetime.timedelta(days=365), help_text='Intervalo máximo entre repasos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_study_contexts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Estudiante'), ('teacher', 'Profesor'), ('observer', 'Observador')], default='student', max_length=20)),
                ('items_completed', models.PositiveIntegerField(default=0)),
                ('total_practice_time', models.DurationField(default=datetime.timedelta(0))),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planificada'), ('active', 'Activa'), ('paused', 'Pausada'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='planned', max_length=20)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='study_sessions.studycontext')),
                ('participants', models.ManyToManyField(related_name='study_sessions', through='study_sessions.StudyParticipation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_start', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='studyparticipation',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_sessions.studysession'),
        ),
        migrations.CreateModel(
            name='SessionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En progreso'), ('completed', 'Completado'), ('skipped', 'Omitido')], default='pending', max_length=20)),
                ('time_spent', models.DurationField(default=datetime.timedelta(0))),
                ('session_notes', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_sessions.studysession')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UniversalStudyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('title', models.CharField(help_text='Título descriptivo del item', max_length=200)),
                ('difficulty_level', models.IntegerField(choices=[(1, 'Nivel 1'), (2, 'Nivel 2'), (3, 'Nivel 3'), (4, 'Nivel 4'), (5, 'Nivel 5')], default=1)),
                ('estimated_practice_time', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_study_items', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='study_items', to='music_cards.tag')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('content_type', 'object_id', 'created_by')},
            },
        ),
        migrations.AddField(
            model_name='studysession',
            name='study_items',
            field=models.ManyToManyField(related_name='study_sessions', through='study_sessions.SessionItem', to='study_sessions.universalstudyitem'),
        ),
        migrations.AddField(
            model_name='sessionitem',
            name='study_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_sessions.universalstudyitem'),
        ),
        migrations.AlterUniqueTogether(
            name='studyparticipation',
            unique_together={('session', 'participant')},
        ),
        migrations.CreateModel(
            name='StudyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_level', models.IntegerField(choices=[(1, 'Nivel 1'), (2, 'Nivel 2'), (3, 'Nivel 3'), (4, 'Nivel 4'), (5, 'Nivel 5')], default=1)),
                ('practice_count', models.PositiveIntegerField(default=0)),
                ('total_practice_time', models.DurationField(default=datetime.timedelta(0))),
                ('last_practiced', models.DateTimeField(auto_now=True)),
                ('next_review_date', models.DateTimeField(blank=True, null=True)),
                ('current_interval', models.DurationField(default=datetime.timedelta(days=1))),
                ('ease_factor', models.FloatField(default=2.5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_sessions.studycontext')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('study_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_sessions.universalstudyitem')),
            ],
            options={
                'ordering': ['next_review_date', '-last_practiced'],
                'unique_together': {('participant', 'study_item', 'context')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='sessionitem',
            unique_together={('session', 'study_item')},
        ),
    ]
