# Generated by Django 5.0.11 on 2025-10-15 06:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studyparticipation',
            index=models.Index(fields=['participant', 'role'], name='study_sessi_partici_0f55b7_idx'),
        ),
        migrations.AddIndex(
            model_name='studyparticipation',
            index=models.Index(fields=['session', 'joined_at'], name='study_sessi_session_b3bf30_idx'),
        ),
        migrations.AddIndex(
            model_name='studyparticipation',
            index=models.Index(fields=['participant', 'joined_at'], name='study_sessi_partici_698a25_idx'),
        ),
        migrations.AddIndex(
            model_name='studyprogress',
            index=models.Index(fields=['participant', 'study_item', 'context'], name='study_sessi_partici_f09847_idx'),
        ),
        migrations.AddIndex(
            model_name='studyprogress',
            index=models.Index(fields=['participant', 'next_review_date'], name='study_sessi_partici_769698_idx'),
        ),
        migrations.AddIndex(
            model_name='studyprogress',
            index=models.Index(fields=['next_review_date'], name='study_sessi_next_re_9167fa_idx'),
        ),
        migrations.AddIndex(
            model_name='studyprogress',
            index=models.Index(fields=['participant', 'mastery_level'], name='study_sessi_partici_1f92e4_idx'),
        ),
        migrations.AddIndex(
            model_name='studyprogress',
            index=models.Index(fields=['context', 'next_review_date'], name='study_sessi_context_b003d8_idx'),
        ),
    ]
