# Generated by Django 5.0.11 on 2025-10-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_sessions', '0002_phase1_strategic_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyparticipation',
            name='average_mastery_level',
            field=models.FloatField(default=0.0, help_text='Nivel promedio de dominio'),
        ),
        migrations.AddField(
            model_name='studyparticipation',
            name='items_mastered',
            field=models.PositiveIntegerField(default=0, help_text='Items con nivel 4-5'),
        ),
        migrations.AddField(
            model_name='studyparticipation',
            name='streak_days',
            field=models.PositiveIntegerField(default=0, help_text='Días consecutivos de práctica'),
        ),
        migrations.AddField(
            model_name='studyparticipation',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0, help_text='Total de repasos realizados'),
        ),
    ]
