# Generated by Django 5.0.11 on 2025-10-15 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
        ('cms', '0003_alter_classsessionpage_course'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('music_cards', '0020_phase2_soft_delete_implementation'),
        ('study_sessions', '0003_phase3_performance_optimizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='universalstudyitem',
            name='class_session_page',
            field=models.ForeignKey(blank=True, help_text='Referencia a página de sesión de clase', null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.classsessionpage'),
        ),
        migrations.AddField(
            model_name='universalstudyitem',
            name='music_item',
            field=models.ForeignKey(blank=True, help_text='Referencia a elemento musical', null=True, on_delete=django.db.models.deletion.CASCADE, to='music_cards.musicitem'),
        ),
        migrations.AddField(
            model_name='universalstudyitem',
            name='student_contribution',
            field=models.ForeignKey(blank=True, help_text='Referencia a contribución estudiantil', null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.studentcontribution'),
        ),
        migrations.AlterField(
            model_name='universalstudyitem',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='universalstudyitem',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
