# Generated by Django 4.2.3 on 2023-07-26 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("music_cards", "0002_rename_authors_author_rename_userreviews_userreview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userreview",
            name="music_item",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_reviews",
                to="music_cards.musicitem",
            ),
            preserve_default=False,
        ),
    ]
