# Generated by Django 4.2.3 on 2023-07-26 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("music_cards", "0003_alter_userreview_music_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userreview",
            name="music_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="user_review", to="music_cards.musicitem"
            ),
        ),
    ]
