# Generated by Django 4.2.3 on 2023-07-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music_cards", "0004_alter_userreview_music_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="surname",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
