# Generated by Django 4.2.3 on 2023-07-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music_cards", "0005_author_surname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstudysession",
            name="reviews",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="study_sessions", to="music_cards.userreview"
            ),
        ),
    ]
