# Generated by Django 5.0.3 on 2024-08-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music_cards", "0006_alter_userstudysession_reviews"),
    ]

    operations = [
        migrations.AddField(
            model_name="embed",
            name="copyrighted",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="file",
            name="copyrighted",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="userstudysession",
            name="reviews",
            field=models.ManyToManyField(
                blank=True, related_name="study_sessions", to="music_cards.userreview"
            ),
        ),
    ]
