# Generated by Django 5.0.3 on 2024-08-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music_cards", "0009_category_embed_category_file_category_text_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["parent__id", "order"]},
        ),
        migrations.AddField(
            model_name="category",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
