# Generated by Django 5.0.3 on 2024-08-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music_cards", "0010_alter_category_options_category_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="embed",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="file",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="text",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
