# Generated by Django 5.0.3 on 2024-08-29 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music_cards", "0011_embed_order_file_order_text_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="embed",
            name="order",
        ),
        migrations.RemoveField(
            model_name="file",
            name="order",
        ),
        migrations.RemoveField(
            model_name="text",
            name="order",
        ),
    ]
