# Generated by Django 5.0.3 on 2024-08-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music_cards", "0012_remove_embed_order_remove_file_order_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="embed",
            name="music_item",
        ),
        migrations.RemoveField(
            model_name="file",
            name="music_item",
        ),
        migrations.RemoveField(
            model_name="musicitem",
            name="author",
        ),
        migrations.RemoveField(
            model_name="text",
            name="music_item",
        ),
        migrations.AddField(
            model_name="musicitem",
            name="embeds",
            field=models.ManyToManyField(
                blank=True, related_name="music_items", to="music_cards.embed"
            ),
        ),
        migrations.AddField(
            model_name="musicitem",
            name="files",
            field=models.ManyToManyField(
                blank=True, related_name="music_items", to="music_cards.file"
            ),
        ),
        migrations.AddField(
            model_name="musicitem",
            name="texts",
            field=models.ManyToManyField(
                blank=True, related_name="music_items", to="music_cards.text"
            ),
        ),
    ]
