# Generated by Django 5.0.3 on 2024-08-31 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music_cards", "0014_categoryitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categoryitem",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="categoryitem",
            name="object_id",
        ),
        migrations.RemoveField(
            model_name="embed",
            name="category",
        ),
        migrations.RemoveField(
            model_name="file",
            name="category",
        ),
        migrations.RemoveField(
            model_name="text",
            name="category",
        ),
        migrations.AddField(
            model_name="category",
            name="embeds",
            field=models.ManyToManyField(
                blank=True, related_name="categories", to="music_cards.embed"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="files",
            field=models.ManyToManyField(
                blank=True, related_name="categories", to="music_cards.file"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="music_items",
            field=models.ManyToManyField(
                blank=True, related_name="categories", to="music_cards.musicitem"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="texts",
            field=models.ManyToManyField(
                blank=True, related_name="categories", to="music_cards.text"
            ),
        ),
        migrations.AddField(
            model_name="categoryitem",
            name="embed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="music_cards.embed",
            ),
        ),
        migrations.AddField(
            model_name="categoryitem",
            name="file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="music_cards.file",
            ),
        ),
        migrations.AddField(
            model_name="categoryitem",
            name="music_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="music_cards.musicitem",
            ),
        ),
        migrations.AddField(
            model_name="categoryitem",
            name="text",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="music_cards.text",
            ),
        ),
    ]
