# Generated by Django 5.0.3 on 2024-08-31 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music_cards", "0015_remove_categoryitem_content_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="embeds",
        ),
        migrations.RemoveField(
            model_name="category",
            name="files",
        ),
        migrations.RemoveField(
            model_name="category",
            name="music_items",
        ),
        migrations.RemoveField(
            model_name="category",
            name="texts",
        ),
    ]
