# Generated by Django 5.0.11 on 2025-09-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_cards', '0017_alter_musicitem_options_musicitem_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='box',
            field=models.IntegerField(choices=[(1, 'No lo sé'), (2, 'Difícil'), (3, 'Bien'), (4, 'Fácil')]),
        ),
    ]
