# Generated by Django 5.0.11 on 2025-10-15 06:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_cards', '0018_alter_userreview_box'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreview',
            old_name='n_times_reiewed',
            new_name='n_times_reviewed',
        ),
        migrations.AddIndex(
            model_name='userreview',
            index=models.Index(fields=['user', 'music_item'], name='music_cards_user_id_c3c593_idx'),
        ),
        migrations.AddIndex(
            model_name='userreview',
            index=models.Index(fields=['user', 'box'], name='music_cards_user_id_ea09d8_idx'),
        ),
        migrations.AddIndex(
            model_name='userreview',
            index=models.Index(fields=['user', 'last_reviewed'], name='music_cards_user_id_e430f5_idx'),
        ),
        migrations.AddIndex(
            model_name='userreview',
            index=models.Index(fields=['box', 'last_reviewed'], name='music_cards_box_94322a_idx'),
        ),
    ]
