# Generated by Django 5.0.11 on 2025-10-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_cards', '0019_phase1_improvements_typo_and_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicitem',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Fecha de borrado lógico', null=True),
        ),
    ]
