# Generated by Django 5.0.11 on 2026-02-10 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0002_load_fixtures'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.CharField(blank=True, default='', max_length=255, verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_recibidas', to='incidencias.tecnico', verbose_name='Asignado a')),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_realizadas', to='incidencias.tecnico', verbose_name='Asignado por')),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_asignaciones', to='incidencias.incidencia', verbose_name='Incidencia')),
            ],
            options={
                'verbose_name': 'Historial de asignación',
                'verbose_name_plural': 'Historial de asignaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
