# Generated by Django 5.0.11 on 2026-02-18 18:03

import django.core.validators
import django.db.models.deletion
import incidencias.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0003_historial_asignacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiAPIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('caller', models.CharField(help_text='Módulo que realizó la llamada (ej: email_parser, ai_metadata)', max_length=100, verbose_name='Caller')),
                ('tokens_used', models.IntegerField(default=0, verbose_name='Tokens usados')),
                ('success', models.BooleanField(default=True, verbose_name='Éxito')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Mensaje de error')),
            ],
            options={
                'verbose_name': 'Uso de Gemini API',
                'verbose_name_plural': 'Usos de Gemini API',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterField(
            model_name='adjunto',
            name='archivo',
            field=models.FileField(upload_to=incidencias.models.adjunto_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'mp4', 'mov', 'avi', 'webm', 'pdf'])], verbose_name='Archivo'),
        ),
        migrations.CreateModel(
            name='ProcessedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, help_text='Cabecera Message-ID del email original', max_length=512, unique=True, verbose_name='Message-ID')),
                ('processed_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de procesado')),
                ('raw_subject', models.CharField(blank=True, default='', max_length=512, verbose_name='Asunto original')),
                ('raw_sender', models.EmailField(blank=True, default='', max_length=254, verbose_name='Remitente original')),
                ('skipped', models.BooleanField(default=False, help_text='True si fue omitido (duplicado, rate limit, etc.)', verbose_name='Omitido')),
                ('skip_reason', models.CharField(blank=True, default='', max_length=200, verbose_name='Razón de omisión')),
                ('incidencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_origen', to='incidencias.incidencia', verbose_name='Incidencia')),
            ],
            options={
                'verbose_name': 'Email procesado',
                'verbose_name_plural': 'Emails procesados',
                'ordering': ['-processed_at'],
            },
        ),
    ]
