# Generated by Django 5.0.11 on 2026-03-11 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0004_geminiapiusage_alter_adjunto_archivo_processedemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjunto',
            name='comentario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='incidencias.comentario', verbose_name='Comentario'),
        ),
    ]
