# Generated by Django 5.0.11 on 2026-09-28 16:06

import django.db.models.deletion
import incidencias.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0005_adjunto_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='Slug')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('que_va_aqui', models.TextField(blank=True, default='', verbose_name='Qué va aquí')),
                ('correos', models.CharField(blank=True, default='', help_text='Separados por coma', max_length=255, verbose_name='Correos')),
                ('telefono', models.CharField(blank=True, default='', max_length=100, verbose_name='Teléfono')),
                ('url_formulario', models.URLField(blank=True, default='', verbose_name='Formulario o web')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('token', models.CharField(default=incidencias.models.nuevo_token, max_length=64, unique=True, verbose_name='Token público')),
                ('orden', models.PositiveSmallIntegerField(default=100, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='incidencia',
            name='ambito',
            field=models.CharField(choices=[('informatica', 'Informática'), ('mantenimiento', 'Mantenimiento y obra'), ('gestion', 'Gestión interna'), ('otro', 'Otro')], default='informatica', max_length=15, verbose_name='Ámbito'),
        ),
        migrations.CreateModel(
            name='Derivacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('respondida', 'Respondida'), ('cerrada', 'Cerrada')], default='borrador', max_length=12, verbose_name='Estado')),
                ('resultado', models.CharField(blank=True, choices=[('resuelta', 'Resuelta'), ('sin_solucion', 'Sin solución'), ('duplicada', 'Duplicada')], default='', max_length=12, verbose_name='Resultado')),
                ('asunto', models.CharField(max_length=255, verbose_name='Asunto')),
                ('cuerpo', models.TextField(blank=True, default='', verbose_name='Cuerpo del correo')),
                ('ticket_externo', models.CharField(blank=True, default='', max_length=100, verbose_name='Ticket externo')),
                ('enviada_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviada el')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivaciones_creadas', to='incidencias.tecnico', verbose_name='Creada por')),
                ('enviada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivaciones_enviadas', to='incidencias.tecnico', verbose_name='Enviada por')),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derivaciones', to='incidencias.incidencia', verbose_name='Incidencia')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derivaciones', to='incidencias.servicio', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Derivación',
                'verbose_name_plural': 'Derivaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comunicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentido', models.CharField(choices=[('enviada', 'Enviada'), ('recibida', 'Recibida'), ('nota', 'Nota')], max_length=10, verbose_name='Sentido')),
                ('canal', models.CharField(choices=[('correo', 'Correo'), ('telefono', 'Teléfono'), ('formulario', 'Formulario web'), ('visita', 'Visita'), ('otro', 'Otro')], default='correo', max_length=12, verbose_name='Canal')),
                ('autor_nombre', models.CharField(blank=True, default='', max_length=150, verbose_name='Autor')),
                ('texto', models.TextField(verbose_name='Texto')),
                ('fecha', models.DateTimeField(help_text='Cuándo ocurrió, no cuándo se apuntó', verbose_name='Fecha')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Apuntada')),
                ('derivacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicaciones', to='incidencias.derivacion', verbose_name='Derivación')),
            ],
            options={
                'verbose_name': 'Comunicación',
                'verbose_name_plural': 'Comunicaciones',
                'ordering': ['fecha', 'id'],
            },
        ),
    ]
