# Generated by Django 5.0.11 on 2026-10-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0007_seed_servicios'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='modo',
            field=models.CharField(choices=[('correo', 'Se le escribe un correo'), ('visita', 'Se apunta y se le llama para que venga')], default='correo', help_text='Un oficio (electricista, carpintería…) se apunta en su lista y se le llama cuando hay bastante', max_length=10, verbose_name='Cómo se le avisa'),
        ),
    ]
