# Generated by Django 5.0.11 on 2026-10-09 06:54

import django.db.models.deletion
from django.db import migrations, models


def marcar_existentes(apps, schema_editor):
    """Las etiquetas de antes ya están revisadas y reciben el color que les toca por slug."""
    # Copia de Etiqueta.color_para en el momento de escribir la migración.
    colores = ["rojo", "naranja", "ambar", "lima", "verde", "turquesa", "cian", "azul", "indigo", "violeta", "fucsia", "rosa"]
    Etiqueta = apps.get_model("incidencias", "Etiqueta")
    for e in Etiqueta.objects.all():
        e.revisada = True
        e.color = colores[sum(ord(c) for c in e.slug) % len(colores)]
        e.save(update_fields=["revisada", "color"])


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0009_seed_oficios'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiqueta',
            name='color',
            field=models.CharField(blank=True, default='', max_length=12, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='etiqueta',
            name='creada_por',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Creada por'),
        ),
        migrations.AddField(
            model_name='etiqueta',
            name='revisada',
            field=models.BooleanField(default=False, help_text='Las que escribe la gente entran sin revisar hasta la pasada semanal', verbose_name='Revisada'),
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('menciona', 'Menciona'), ('unida', 'Unida a')], default='menciona', max_length=10, verbose_name='Tipo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('comentario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referencias', to='incidencias.comentario', verbose_name='Comentario')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias_entrantes', to='incidencias.incidencia', verbose_name='Hacia')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias_salientes', to='incidencias.incidencia', verbose_name='Desde')),
            ],
            options={
                'verbose_name': 'Referencia',
                'verbose_name_plural': 'Referencias',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='referencia',
            constraint=models.UniqueConstraint(fields=('origen', 'destino', 'tipo'), name='referencia_unica'),
        ),
        migrations.RunPython(marcar_existentes, migrations.RunPython.noop),
    ]
