#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

if [ -z "${POSTGRES_USER}" ]; then
    base_postgres_image_default_user='postgres'
    export POSTGRES_USER="${base_postgres_image_default_user}"
fi
export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

wait-for-it "${POSTGRES_HOST}:${POSTGRES_PORT}" -t 30

>&2 echo 'PostgreSQL is available'

# Archivos CSS fuente de Tailwind que pueden causar conflicto con Whitenoise
SOURCE_CSS_FILE_1="/app/martina_bescos_app/static/css/index.css"
SOURCE_CSS_FILE_2="/app/martina_bescos_app/static/css/input.css" # <-- Archivo adicional
# Archivo CSS compilado por Tailwind
COMPILED_CSS_FILE="/app/martina_bescos_app/static/css/output.css"

# --- Eliminar archivos fuente ---
# Eliminar index.css si existe
if [ -f "$SOURCE_CSS_FILE_1" ]; then
  echo "Temporarily removing source CSS file: $SOURCE_CSS_FILE_1"
  rm "$SOURCE_CSS_FILE_1"
else
  echo "Source CSS file 1 not found, skipping removal: $SOURCE_CSS_FILE_1"
fi

# Eliminar input.css si existe <-- NUEVO
if [ -f "$SOURCE_CSS_FILE_2" ]; then
  echo "Temporarily removing source CSS file: $SOURCE_CSS_FILE_2"
  rm "$SOURCE_CSS_FILE_2"
else
  echo "Source CSS file 2 not found, skipping removal: $SOURCE_CSS_FILE_2"
fi
# --- Fin de eliminar archivos fuente ---


# Verificar si el archivo compilado existe (¡debería!)
if [ ! -f "$COMPILED_CSS_FILE" ]; then
  echo "ERROR: Compiled CSS file not found: $COMPILED_CSS_FILE"
  echo "Check the 'npm run build' step in the Dockerfile build process."
  exit 1
fi


>&2 echo "Running collectstatic..."
# Ejecuta collectstatic usando el usuario 'django' (definido en Dockerfile)
# Necesita permisos de escritura en STATIC_ROOT (/app/staticfiles por defecto)
python /app/manage.py collectstatic --noinput


exec "$@"
