#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# python /app/manage.py collectstatic --noinput # <-- ELIMINAR ESTA LÍNEA

# Migraciones (Opcional, mejor manejarlas explícitamente o en entrypoint si es necesario)
# python /app/manage.py migrate --noinput

echo "Starting Gunicorn..."
exec /usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app --timeout 300