# Generated by Django 5.0.11 on 2026-02-16 12:44

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, help_text='Emoji o clase de icono CSS', max_length=50, verbose_name='Icono')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content_hub.category', verbose_name='Categoría padre')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContentCategoryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_hub.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Orden de contenido en categoría',
                'verbose_name_plural': 'Órdenes de contenido en categorías',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('song', 'Canción'), ('author', 'Autor/Compositor'), ('album', 'Álbum/Colección'), ('pdf', 'PDF/Partitura'), ('audio', 'Audio'), ('image', 'Imagen'), ('video', 'Vídeo'), ('embed', 'Embed (Hooktheory, YouTube, etc.)'), ('url', 'URL/Enlace'), ('note', 'Nota/Texto libre'), ('exercise', 'Ejercicio')], db_index=True, max_length=20, verbose_name='Tipo de contenido')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='content_hub/%Y/%m/', verbose_name='Archivo')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='URL')),
                ('text_content', models.TextField(blank=True, help_text='Para notas, ejercicios, HTML de embeds', verbose_name='Contenido de texto')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos estructurados según el tipo de contenido', verbose_name='Metadatos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('is_archived', models.BooleanField(default=False, help_text='Contenido archivado no aparece en búsquedas', verbose_name='Archivado')),
                ('categories', models.ManyToManyField(blank=True, through='content_hub.ContentCategoryOrder', to='content_hub.category', verbose_name='Categorías')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_content', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Etiquetas')),
            ],
            options={
                'verbose_name': 'Elemento de contenido',
                'verbose_name_plural': 'Elementos de contenido',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='contentcategoryorder',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_hub.contentitem', verbose_name='Contenido'),
        ),
        migrations.CreateModel(
            name='ContentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('related', 'Relacionado con'), ('part_of', 'Es parte de'), ('derived', 'Derivado de'), ('reference', 'Hace referencia a'), ('created_by', 'Creado por'), ('contains', 'Contiene'), ('prerequisite', 'Requiere conocer')], default='related', max_length=20, verbose_name='Tipo de enlace')),
                ('notes', models.TextField(blank=True, help_text='Contexto adicional del enlace', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='content_hub.contentitem', verbose_name='Origen')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='content_hub.contentitem', verbose_name='Destino')),
            ],
            options={
                'verbose_name': 'Enlace de contenido',
                'verbose_name_plural': 'Enlaces de contenido',
            },
        ),
        migrations.AddField(
            model_name='contentitem',
            name='linked_to',
            field=models.ManyToManyField(blank=True, through='content_hub.ContentLink', to='content_hub.contentitem'),
        ),
        migrations.AlterUniqueTogether(
            name='contentcategoryorder',
            unique_together={('content', 'category')},
        ),
        migrations.AddIndex(
            model_name='contentlink',
            index=models.Index(fields=['link_type'], name='content_hub_link_ty_e55505_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contentlink',
            unique_together={('source', 'target', 'link_type')},
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['content_type', 'is_archived'], name='content_hub_content_c302e9_idx'),
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['created_at'], name='content_hub_created_88bc33_idx'),
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['updated_at'], name='content_hub_updated_cdec34_idx'),
        ),
    ]
