# Generated by Django 5.0.11 on 2026-09-23 10:50

import calificaciones.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clases', '0018_group_idioma'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(help_text='Ej: 3º ESO', max_length=50, verbose_name='Nivel')),
                ('modalidad', models.CharField(blank=True, help_text='Ej: bilingüe', max_length=50, verbose_name='Modalidad')),
                ('academic_year', models.CharField(max_length=20, verbose_name='Curso académico')),
                ('peso_trimestres', models.JSONField(blank=True, default=dict, help_text='Ej: {"1": 20, "2": 30, "3": 50}. Vacío = a partes iguales', verbose_name='Peso de los trimestres')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marcos_evaluacion', to='clases.subject')),
            ],
            options={
                'verbose_name': 'Marco de evaluación',
                'verbose_name_plural': 'Marcos de evaluación',
                'ordering': ['academic_year', 'nivel', 'modalidad'],
                'unique_together': {('subject', 'nivel', 'modalidad', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: 3.1', max_length=10, verbose_name='Código')),
                ('competencia', models.CharField(blank=True, help_text='Ej: CE.MU.3', max_length=20, verbose_name='Competencia específica')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('peso', models.DecimalField(decimal_places=2, help_text='El de la programación', max_digits=5, verbose_name='Peso (%)')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('marco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios', to='calificaciones.marcoevaluacion')),
            ],
            options={
                'verbose_name': 'Criterio de evaluación',
                'verbose_name_plural': 'Criterios de evaluación',
                'ordering': ['marco', 'orden', 'codigo'],
                'unique_together': {('marco', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, help_text='Vacío = sin nota. No es lo mismo que cero', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('10'))])),
                ('comentario', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_calificaciones', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
            },
        ),
        migrations.CreateModel(
            name='CambioNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antes', models.CharField(blank=True, max_length=20)),
                ('despues', models.CharField(blank=True, max_length=20)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('revertido_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversiones', to='calificaciones.cambionota')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios', to='calificaciones.nota')),
            ],
            options={
                'verbose_name': 'Cambio de nota',
                'verbose_name_plural': 'Historial de notas',
                'ordering': ['-ts', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.PositiveSmallIntegerField(choices=[(1, '1ª evaluación'), (2, '2ª evaluación'), (3, '3ª evaluación')])),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='planes_calificacion', to='clases.group', verbose_name='Grupos')),
                ('marco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes', to='calificaciones.marcoevaluacion')),
            ],
            options={
                'verbose_name': 'Plan de calificación',
                'verbose_name_plural': 'Planes de calificación',
                'ordering': ['marco', 'trimestre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre')),
                ('abreviatura', models.CharField(max_length=12, verbose_name='Abreviatura')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('escala', models.CharField(choices=[('numerica', 'Numérica 0-10'), ('opciones', 'Lista de opciones')], default='numerica', max_length=10)),
                ('opciones', models.JSONField(blank=True, default=list)),
                ('agregacion', models.CharField(choices=[('media', 'Media de las pruebas'), ('ultima', 'La última prueba'), ('mejor', 'La mejor prueba')], default='media', max_length=10)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrumentos', to='calificaciones.plan')),
            ],
            options={
                'verbose_name': 'Instrumento de evaluación',
                'verbose_name_plural': 'Instrumentos de evaluación',
                'ordering': ['plan', 'orden', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas', to='calificaciones.instrumento')),
            ],
            options={
                'verbose_name': 'Prueba',
                'verbose_name_plural': 'Pruebas',
                'ordering': ['fecha', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='nota',
            name='prueba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='calificaciones.prueba'),
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('foto', 'Foto'), ('audio', 'Audio'), ('video', 'Vídeo'), ('texto', 'Nota de texto'), ('enlace', 'Enlace')], max_length=10)),
                ('archivo', models.FileField(blank=True, max_length=255, upload_to=calificaciones.models.ruta_evidencia)),
                ('archivo_comprimido', models.FileField(blank=True, max_length=255, upload_to=calificaciones.models.ruta_evidencia)),
                ('tipo_mime', models.CharField(blank=True, max_length=80)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('listo', 'Listo'), ('fallido', 'Fallido')], default='listo', max_length=10)),
                ('error', models.TextField(blank=True)),
                ('texto', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias_calificaciones', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='calificaciones.prueba')),
            ],
            options={
                'verbose_name': 'Evidencia',
                'verbose_name_plural': 'Evidencias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotaManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambito', models.CharField(choices=[('1', '1ª evaluación'), ('2', '2ª evaluación'), ('3', '3ª evaluación'), ('curso', 'Final de curso')], max_length=5)),
                ('calificacion', models.CharField(choices=[('IN', 'Insuficiente'), ('SU', 'Suficiente'), ('BI', 'Bien'), ('NT', 'Notable'), ('SB', 'Sobresaliente')], max_length=2)),
                ('motivo', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_manuales', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_manuales', to='clases.group')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota manual',
                'verbose_name_plural': 'Notas manuales',
                'unique_together': {('group', 'alumno', 'ambito')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together={('prueba', 'alumno')},
        ),
        migrations.CreateModel(
            name='Reparto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repartos', to='calificaciones.criterio')),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repartos', to='calificaciones.instrumento')),
            ],
            options={
                'verbose_name': 'Reparto',
                'verbose_name_plural': 'Reparto',
                'unique_together': {('instrumento', 'criterio')},
            },
        ),
    ]
