# Generated by Django 5.0.11 on 2026-09-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='hueco_cuenta_cero',
            field=models.BooleanField(db_default=True, default=True, help_text='Sin marcar, lo que no tiene nota no cuenta y la media se hace con el resto', verbose_name='Una celda vacía cuenta como 0'),
        ),
    ]
