# Generated by Django 5.0.11 on 2026-09-29 14:40

from django.db import migrations, models


def rellenar_tamano(apps, schema_editor):
    """El peso de las evidencias que ya existen. Si un fichero no está, se queda en 0."""
    Evidencia = apps.get_model("calificaciones", "Evidencia")
    for evidencia in Evidencia.objects.exclude(archivo="", archivo_comprimido=""):
        fichero = evidencia.archivo_comprimido or evidencia.archivo
        try:
            evidencia.tamano = fichero.size
        except (OSError, ValueError):
            continue
        evidencia.save(update_fields=["tamano"])


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0002_hueco_cuenta_cero'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencia',
            name='nombre_original',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='tamano',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='tipo',
            field=models.CharField(choices=[('foto', 'Foto'), ('audio', 'Audio'), ('video', 'Vídeo'), ('texto', 'Nota de texto'), ('enlace', 'Enlace'), ('archivo', 'Archivo')], max_length=10),
        ),
        migrations.RunPython(rellenar_tamano, migrations.RunPython.noop),
    ]
