# Generated by Django 5.0.11 on 2026-10-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0003_evidencia_nombre_y_tamano'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumento',
            name='rubrica',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='nota',
            name='rubrica',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
