# Generated by Django 5.0.11 on 2026-10-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0004_rubrica'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencia',
            name='grabacion',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
